---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

configMapGenerator:
  - name: olah-configmap
    files:
      - configmap/configs.toml
  - name: olah-scripts-configmap
    files:
      - configmap/cache_guard.py
resources:
  - deployment.yml
  - service.yml
