---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: kube-dns
  name: coredns-servicemonitor
spec:
  endpoints:
    - port: metrics
  selector:
    matchLabels:
      k8s-app: kube-dns
