ARG PARENT

# Allow build scripts to be referenced without being copied into the final image.
FROM scratch AS ctx
COPY build_files /

FROM --platform=linux/arm64 $PARENT

RUN --mount=type=bind,from=ctx,source=/,target=/ctx \
    --mount=type=cache,dst=/var/cache \
    --mount=type=cache,dst=/var/log \
    --mount=type=tmpfs,dst=/tmp \
    /ctx/build.sh && \
    ostree container commit

# Verify final image and contents are correct.
RUN bootc container lint
