---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

components:
  - ../base
  - ../ups02
namePrefix: workers-
patches:
  - path: patches/add_workers_settings.yml
    target:
      kind: DaemonSet
      name: nut-shutdown-agent-daemonset
