---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-to-snmp-networkpolicy
spec:
  egress: []
  podSelector:
    matchLabels:
      app.kubernetes.io/name: network-ups-tools
  policyTypes:
    - Egress
