---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

images:
  - name: ghcr.io/authelia/authelia
    newTag: 4.39.27@sha256:ea6ddce051110a0459b9393117a86383771269aac72f89cabe07f3e9e07f892d 
resources:
  - deployment.yml
  - service.yml
  - podmonitor.yml
