---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

images:
  - name: ghcr.io/authelia/authelia
    newTag: 4.39.18@sha256:ac379ba7680cea6ea21a29b65bf6daabb5aec5b4412c5591ec71df4fd156c789 
resources:
  - deployment.yml
  - service.yml
  - podmonitor.yml
