---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

images:
  - name: ghcr.io/authelia/authelia
    newTag: 4.39.20@sha256:1b363e9279e742397966333f364e0876ae02bf5c876de73e83af6d48c57ff51b 
resources:
  - deployment.yml
  - service.yml
  - podmonitor.yml
