---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: this-is-ignored-but-is-required
spec:
  template:
    spec:
      containers:
        - name: llama-server
          env: &models
            - name: MODELS
              valueFrom:
                configMapKeyRef:
                  key: MODELS
                  name: local-llm-models-configmap
      initContainers:
        - name: fetch-model
          env: *models
