---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: this-is-ignored-but-is-required
spec:
  template:
    spec:
      containers:
        - env:
            - name: REGISTRY_HTTP_DEBUG_PROMETHEUS_ENABLED
              value: "true"
            # - name: REGISTRY_LOG_LEVEL
            #   value: debug
            - name: REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY
              value: /var/lib/registry
          name: ttl-registry
          volumeMounts:
            - name: registry-data
              mountPath: /var/lib/registry
      volumes:
        # This throws away all data on every restart!
        - name: registry-data
          emptyDir: {}
