---
- op: add
  path: /spec/ingress/0/ports/-
  value:
    port: grafana
# Loki's Ingress points to `http-metrics` port, which confusingly services more
# than just metrics.
- op: add
  path: /spec/ingress/0/ports/-
  value:
    port: http-metrics
