---
# For reference: https://code.forgejo.org/forgejo/runner/src/branch/main/internal/pkg/config/config.example.yaml
cache:
  # Might be nice, but for a one-shot runner, useless to configure without a remote server.
  enabled: false
container:
  docker_host: "-"
  enable_ipv6: false
  force_pull: false
  force_rebuild: false
  network: host
  options: -v /certs/client:/certs/client
  privileged: true
  valid_volumes:
    - /certs/client
  workdir_parent:
log:
  job_level: info
  level: info
runner:
  envs:
    DOCKER_CERT_PATH: /certs/client
    DOCKER_HOST: tcp://127.0.0.1:2376
    DOCKER_TLS_VERIFY: 1
  insecure: false
  labels:
    - ci-latest:docker://ghcr.io/marinatedconcrete/github-runner-ci:1.1.0
    - fedora-latest:docker://ghcr.io/marinatedconcrete/devcontainer-base:latest
    - node:docker://node:lts
    - ubuntu-latest:docker://ghcr.io/catthehacker/ubuntu:act-24.04
  timeout: 3h
server:
  connections:
    hogs-prod:
      url: https://code.tswn.us/
      uuid: ba0da30a-18a4-41bd-b96c-09fb655bf708
      token_url: file:/secrets/runner/token
