---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

images:
  - name: lscr.io/linuxserver/tvheadend
    newTag: latest@sha256:04caf2d70776233154fff1a184647c72068b3aa1593f3576c1c9ea3a755ae18c
resources:
  - service.yml
  - statefulset.yml
