---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

images:
  - name: lscr.io/linuxserver/tvheadend
    newTag: latest@sha256:7c26fee0422833f4856135ff8fa792f8d07bc420abb3ad3ce90d3a26a4911202
resources:
  - service.yml
  - statefulset.yml
