---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

images:
  - name: lscr.io/linuxserver/tvheadend
    newTag: latest@sha256:ab7cec3ed7692358701f130a0b9ac882e5b989ea21e3cb10470003fb296dfebe
resources:
  - service.yml
  - statefulset.yml
