---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

components:
  - ../../../components/cnpg-backup
configMapGenerator:
  - name: crowdsec-configmap
    files:
      - configmap/config.yaml.local
  - name: crowdsec-acquisitions-configmap
    files:
      - configmap/acquis.d/appsec.yaml
      - configmap/acquis.d/authelia.yaml
      - configmap/acquis.d/immich.yaml
      - configmap/acquis.d/navidrome.yaml
      - configmap/acquis.d/traefik.yaml
  - name: crowdsec-scripts-configmap
    files:
      - configmap/scripts/entrypoint.sh
images:
  - name: ghcr.io/crowdsecurity/crowdsec
    newTag: v1.7.7@sha256:6ca53ad26196ca59ddd4fa692a586b73d8fcde085046163b9ca2f04887dca563 
  - name: postgres
    newTag: 18@sha256:78481659c47e862334611ccdaf7c369c986b3046da9857112f3b309114a65fb4
namespace: crowdsec
patches:
  - path: patches/cnpg/set_backup_path.yml
    target:
      kind: ObjectStore
      name: garage-objectstore
resources:
  - namespace.yml
  - cnpg/cluster.yml
  - cnpg/podmonitor.yml
  - cnpg/scheduledbackup.yml
  - deployment.yml
  - service.yml
