---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

components:
  - ../../../components/cnpg-backup
  - ../../../components/cnpg-podmonitor
  - ../../../components/networkpolicy-allow-from-cnpg-operator
  - ../../../components/networkpolicy-allow-from-prometheus
  - ../../../components/networkpolicy-allow-from-prometheus-to-cnpg-cluster
  - ../../../components/networkpolicy-allow-from-traefik
  - ../../../components/networkpolicy-allow-to-api-server
  - ../../../components/networkpolicy-allow-to-coredns
  - ../../../components/networkpolicy-allow-to-internet
  - ../../../components/networkpolicy-allow-to-loki
  - ../../../components/networkpolicy-allow-within-this-namespace
  - ../../../components/networkpolicy-deny-all
  - ../../../components/pod-security-enforce-baseline
configMapGenerator:
  - name: crowdsec-configmap
    files:
      - configmap/config.yaml.local
  - name: crowdsec-acquisitions-configmap
    files:
      - configmap/acquis.d/appsec.yaml
      - configmap/acquis.d/authelia.yaml
      - configmap/acquis.d/immich.yaml
      - configmap/acquis.d/jellyfin.yaml
      - configmap/acquis.d/navidrome.yaml
      - configmap/acquis.d/traefik.yaml
      - configmap/acquis.d/unifi.yaml
  - name: crowdsec-scripts-configmap
    files:
      - configmap/scripts/entrypoint.sh
images:
  - name: docker.io/bitnami/kubectl
    newTag: latest@sha256:6e9c5284a0dac06e84de9f4d97852d2e6513442ee7ec3a66d35009eec86e1e62
  - name: ghcr.io/crowdsecurity/crowdsec
    newTag: v1.8.1@sha256:0f2523fa61ef507f15d953045cface490cc880670c62f2755ced17524107f71a 
  - name: postgres
    newTag: 18@sha256:86c951e05bf56c93d95d397747fb8820ac76cc3bedb78f43abd83eedbe3666ae
namespace: crowdsec
patches:
  - path: patches/cnpg/set_backup_path.yml
    target:
      kind: ObjectStore
      name: garage-objectstore
  - path: patches/set_traefik_networkpolicy_ports.yml
    target:
      kind: NetworkPolicy
      name: allow-from-traefik-networkpolicy
resources:
  - namespace.yml
  - cnpg/backup.yml
  - cnpg/cluster.yml
  - cnpg/scheduledbackup.yml
  - deployment.yml
  - podmonitor.yml
  - service.yml
