---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

components:
  - ../../../components/cnpg-backup
configMapGenerator:
  - name: crowdsec-configmap
    files:
      - configmap/config.yaml.local
  - name: crowdsec-acquisitions-configmap
    files:
      - configmap/acquis.d/appsec.yaml
      - configmap/acquis.d/authelia.yaml
      - configmap/acquis.d/immich.yaml
      - configmap/acquis.d/navidrome.yaml
      - configmap/acquis.d/traefik.yaml
  - name: crowdsec-scripts-configmap
    files:
      - configmap/scripts/entrypoint.sh
images:
  - name: docker.io/bitnami/kubectl
    newTag: latest@sha256:9c362260ef11ec664c36f34e0cb263b5cacd5b2f64e4c9b93aa3c3dc95549315
  - name: ghcr.io/crowdsecurity/crowdsec
    newTag: v1.7.8@sha256:2f527c9bb8b367120eb08b82890aa912ce96bfa1ada93dda0721700e4b4e0dde 
  - name: postgres
    newTag: 18@sha256:8ff36f3c66371cba71d20ceedccfc3de9669a68737607888c4ef0af93abe8e39
namespace: crowdsec
patches:
  - path: patches/cnpg/set_backup_path.yml
    target:
      kind: ObjectStore
      name: garage-objectstore
resources:
  - namespace.yml
  - cnpg/backup.yml
  - cnpg/cluster.yml
  - cnpg/podmonitor.yml
  - cnpg/scheduledbackup.yml
  - deployment.yml
  - service.yml
