---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

configMapGenerator:
  - name: code-workspace-configmap
    files:
      - configmap/homeassistant.code-workspace
  - name: scripts-configmap
    files:
      - configmap/scripts/generate_config.sh
      - configmap/scripts/generate_generic_hygrostat_config.sh
      - configmap/scripts/generate_http_config.sh
      - configmap/scripts/generate_recorder_config.sh
      - configmap/scripts/manage_hacs.sh
images:
  - name: ghcr.io/home-assistant/home-assistant
    newTag: 2025.3.1@sha256:304e6999282c5512939db671e5fcbaa923a1f7c9a6e3990cb5baff7abcb9ac4b
  - name: lscr.io/linuxserver/code-server
    newTag: 4.97.2@sha256:733c98b11faf45078c2a98cb1049fa10f386a725c893e867b82b4349ad4c5944
resources:
  - service.yml
  - statefulset.yml
