apiVersion: v1
kind: Namespace
metadata:
  labels:
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/enforce-version: latest
  name: bifrost
---
apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: garage-objectstore
  namespace: bifrost
spec:
  configuration:
    data:
      compression: gzip
    destinationPath: s3://prod-cnpg-backup/bifrost/
    endpointURL: http://garage.garage.svc.cluster.local:3900
    s3Credentials:
      accessKeyId:
        key: ACCESS_KEY_ID
        name: garage-access-secret
      secretAccessKey:
        key: ACCESS_SECRET_KEY
        name: garage-access-secret
    wal:
      compression: gzip
  instanceSidecarConfiguration:
    env:
    - name: AWS_DEFAULT_REGION
      value: hogs
    - name: AWS_REGION
      value: hogs
    - name: AWS_REQUEST_CHECKSUM_CALCULATION
      value: when_required
    - name: AWS_RESPONSE_CHECKSUM_VALIDATION
      value: when_required
    - name: TZ
      value: America/Los_Angeles
    logLevel: info
    retentionPolicyIntervalSeconds: 1800
  retentionPolicy: 30d
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: bifrost-pg-cluster
  namespace: bifrost
spec:
  backup:
    target: primary
  bootstrap:
    initdb:
      builtinLocale: C.UTF-8
      dataChecksums: true
      database: bifrost
      encoding: UTF8
      localeProvider: builtin
      owner: bifrost
  env:
  - name: TZ
    value: America/Los_Angeles
  imageName: ghcr.io/cloudnative-pg/postgresql:18@sha256:899d3ed526b659d77935dde0e6bf2d69dbbf17d3d8c6486ca8cfd04bd3c18533
  instances: 3
  managed:
    services:
      disabledDefaultServices:
      - r
      - ro
  monitoring:
    tls:
      enabled: true
  plugins:
  - enabled: true
    isWALArchiver: true
    name: barman-cloud.cloudnative-pg.io
    parameters:
      barmanObjectName: garage-objectstore
  postgresql:
    parameters:
      max_slot_wal_keep_size: 4GB
    synchronous:
      failoverQuorum: true
      method: any
      number: 1
  primaryUpdateMethod: switchover
  primaryUpdateStrategy: unsupervised
  priorityClassName: application-infra
  storage:
    size: 32Gi
    storageClass: cnpg-data-encrypted-storage
  walStorage:
    size: 16Gi
    storageClass: cnpg-wal-encrypted-storage
