---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: kube-vip-podmonitor
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: kube-vip-svc-ds
  podMetricsEndpoints:
    - portNumber: 2112
      path: /metrics
