---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

images:
  - name: ghcr.io/dancwilliams/protonmail-bridge-docker
    newTag: v3.27.0@sha256:f2c1b0d88ae78e5fbbfd47e6652fc2d8993e02319e5e06028d2cb04766716dcd
resources:
  - service.yml
  - statefulset.yml
