---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

images:
  - name: ghcr.io/dancwilliams/protonmail-bridge-docker
    newTag: v3.27.1@sha256:09b756bc8728ad0c19132add1a7561a3dc378a13182bcebd3e5a30299ab44c50
resources:
  - service.yml
  - statefulset.yml
