---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

components:
  - ../../../components/networkpolicy-allow-from-bifrost
  - ../../../components/networkpolicy-allow-to-coredns
  - ../../../components/networkpolicy-allow-to-olah
  - ../../../components/networkpolicy-deny-all
  - ../../../components/pod-security-enforce-restricted
configMapGenerator:
  - name: local-llm-scripts-configmap
    files:
      - configmap/fetch-model.sh
images:
  - name: docker.io/curlimages/curl
    newTag: 8.22.0@sha256:58adaa4e8dca9c988bae2aba4ab3434a0bb2da16bbe3f92dec39ec7785166777
  - name: ghcr.io/sdwilsh/sif
    newTag: latest@sha256:e21c4d4188a5d3643e740254ac2feb6b38553bf7fdc2eb8dd8232846a4646326
namespace: local-llm
resources:
  - namespace.yml
  - ./llama-group-a
