---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

components:
  - ../../../components/networkpolicy-allow-from-bifrost
  - ../../../components/networkpolicy-allow-to-coredns
  - ../../../components/networkpolicy-allow-to-olah
  - ../../../components/networkpolicy-deny-all
  - ../../../components/pod-security-enforce-restricted
configMapGenerator:
  - name: local-llm-scripts-configmap
    files:
      - configmap/fetch-model.sh
images:
  - name: docker.io/curlimages/curl
    newTag: 8.22.0@sha256:58adaa4e8dca9c988bae2aba4ab3434a0bb2da16bbe3f92dec39ec7785166777
  - name: ghcr.io/ggml-org/llama.cpp
    newTag: full-vulkan-b10902@sha256:33ed2a8936e94ac893a50eed3d2958141d352198233d107e58c1c7ee3b96a9b4
namespace: local-llm
resources:
  - namespace.yml
  - service.yml
  - statefulset.yml
