---
apiVersion: v1
kind: Service
metadata:
  name: local-llm-svc
spec:
  ports:
    - name: web
      port: 8080
      protocol: TCP
      targetPort: web
  selector:
    app.kubernetes.io/name: local-llm
