---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

images:
  - name: mbround18/valheim
    newTag: 3.8.9@sha256:a591678efca90a0ecddc3bff5f6249bf68ae603d297733b4f367f81bb86caf16
resources:
  - statefulset.yml
  - service.yml
