---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

images:
  - name: mbround18/valheim
    newTag: 3.6.0@sha256:abb98466d453f128b96e41d9730cd52f2938013cae7980ce6d3dccc14168d228
resources:
  - statefulset.yml
  - service.yml
