---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

images:
  - name: mbround18/valheim
    newTag: 3.8.4@sha256:51569530f7e6b345546958e255fed77c1ccb48624c7af1117455a7b4e0e794f2
resources:
  - statefulset.yml
  - service.yml
