---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  labels:
    kustomize.hogs.tswn.us/cnpg-podmonitor: "true"
  name: cnpg-podmonitor
spec:
  podMetricsEndpoints:
    - port: metrics
      scheme: https
      tlsConfig:
        ca:
          secret:
            key: ca.crt
            name: cnpg-ca
        serverName: cnpg-rw
  selector:
    matchLabels:
      cnpg.io/cluster: cnpg
