---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: manager-role
  labels:
    app.kubernetes.io/name: forgejo-runner-operator
    app.kubernetes.io/component: controller-manager
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - serviceaccounts
      - services
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - ""
    resources:
      - pods/ephemeralcontainers
    verbs:
      - patch
      - update
  - apiGroups:
      - ""
    resources:
      - pods/log
    verbs:
      - get
  - apiGroups:
      - ""
      - events.k8s.io
    resources:
      - events
    verbs:
      - create
      - patch
  - apiGroups:
      - forgejo.tswn.us
    resources:
      - connections
      - workers
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - forgejo.tswn.us
    resources:
      - connections/finalizers
      - workers/finalizers
    verbs:
      - update
  - apiGroups:
      - forgejo.tswn.us
    resources:
      - connections/status
      - workers/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - monitoring.coreos.com
    resources:
      - podmonitors
      - servicemonitors
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - rolebindings
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - roles
    verbs:
      - bind
      - create
      - delete
      - escalate
      - get
      - list
      - patch
      - update
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: manager-rolebinding
  labels:
    app.kubernetes.io/name: forgejo-runner-operator
    app.kubernetes.io/component: controller-manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: manager-role
subjects:
  - kind: ServiceAccount
    name: controller-manager
    namespace: forgejo-runner-operator
