---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

components:
  - ../../../components/cnpg-backup
  - ../../../components/paperless
images:
  - name: docker.io/bitnami/kubectl
    newTag: latest@sha256:9c362260ef11ec664c36f34e0cb263b5cacd5b2f64e4c9b93aa3c3dc95549315
  - name: postgres
    newTag: 18@sha256:f7ce845ee6873dd84be93c9828fe0d1fab0f9707dc9ac569694657398b290bce
  - name: quay.io/opstree/redis
    newTag: v8.6.2@sha256:5f79911253cb74636e8e97555b08095902d46a835c6423adb123295b00ba70d7
namespace: paperless
patches:
  # cnpg
  - path: patches/cnpg/set_backup_path.yml
    target:
      kind: ObjectStore
      name: garage-objectstore
  # paperless
  - path: patches/increase_paperless_data_size.yml
    target:
      kind: PersistentVolumeClaim
      name: paperless-data
  - path: patches/increase_paperless_media_size.yml
    target:
      kind: PersistentVolumeClaim
      name: paperless-media
  - path: patches/set_paperless_customizations.yml
    target:
      kind: StatefulSet
      name: paperless
  - path: patches/set_samba_address.yml
    target:
      kind: Service
      name: samba-svc
  - path: patches/use_important_longhorn_group.yml
    target:
      kind: PersistentVolumeClaim
resources:
  - namespace.yml
  - cnpg/backup.yml
  - cnpg/cluster.yml
  - cnpg/podmonitor.yml
  - cnpg/scheduledbackup.yml
  - ingress.yml
  - redis.yml
