---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

components:
  - ../../../components/cnpg-backup
  - ../../../components/paperless
images:
  - name: postgres
    newTag: 17@sha256:b994732fcf33f73776c65d3a5bf1f80c00120ba5007e8ab90307b1a743c1fc16
  - name: quay.io/opstree/redis
    newTag: v8.4.2@sha256:eba9bac8aab170698b7276ba1608ad40268ef597c73925576a533940e49287db
namespace: paperless
patches:
  # cnpg
  - path: patches/cnpg/set_backup_path.yml
    target:
      kind: ObjectStore
      name: garage-objectstore
  # paperless
  - path: patches/increase_paperless_data_size.yml
    target:
      kind: PersistentVolumeClaim
      name: paperless-data
  - path: patches/increase_paperless_media_size.yml
    target:
      kind: PersistentVolumeClaim
      name: paperless-media
  - path: patches/set_paperless_customizations.yml
    target:
      kind: StatefulSet
      name: paperless
  - path: patches/set_samba_address.yml
    target:
      kind: Service
      name: samba-svc
  - path: patches/use_important_longhorn_group.yml
    target:
      kind: PersistentVolumeClaim
resources:
  - namespace.yml
  - cnpg/cluster.yml
  - cnpg/podmonitor.yml
  - cnpg/scheduledbackup.yml
  - ingress.yml
  - redis.yml
