---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

components:
  - ../../../components/cnpg-backup
  - ../../../components/paperless
images:
  - name: docker.io/bitnami/kubectl
    newTag: latest@sha256:323998cf83a2332f6761706df910870a3fa24dd8d4b999db977aa322de553399
  - name: postgres
    newTag: 18@sha256:29ee7bb30d804447dc9a91fd0d74322ae1dc3a4072cc6346f70a5ed6e783b565
  - name: quay.io/opstree/redis
    newTag: v8.6.2@sha256:5f79911253cb74636e8e97555b08095902d46a835c6423adb123295b00ba70d7
namespace: paperless
patches:
  # cnpg
  - path: patches/cnpg/set_backup_path.yml
    target:
      kind: ObjectStore
      name: garage-objectstore
  # paperless
  - path: patches/increase_paperless_data_size.yml
    target:
      kind: PersistentVolumeClaim
      name: paperless-data
  - path: patches/increase_paperless_media_size.yml
    target:
      kind: PersistentVolumeClaim
      name: paperless-media
  - path: patches/set_paperless_customizations.yml
    target:
      kind: StatefulSet
      name: paperless
  - path: patches/set_samba_address.yml
    target:
      kind: Service
      name: samba-svc
  - path: patches/use_important_longhorn_group.yml
    target:
      kind: PersistentVolumeClaim
resources:
  - namespace.yml
  - cnpg/backup.yml
  - cnpg/cluster.yml
  - cnpg/podmonitor.yml
  - cnpg/scheduledbackup.yml
  - ingress.yml
  - redis.yml
