---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

components:
  - ../../../components/networkpolicy-allow-to-api-server
  - ../../../components/networkpolicy-allow-to-coredns
  - ../../../components/networkpolicy-deny-all
images:
  - name: ghcr.io/sdwilsh/nut-shutdown-agent
    newTag: latest@sha256:379575fbb2ff791e8743620ecfdc0b9da4ea7ed058320e7c7b207fc21d68ac8b
namespace: nut-shutdown-agent
resources:
  - namespace.yml
  - control-plane
  - networkpolicy/allow-to-nut.yml
  - rbac.yml
  - worker01
  - workers
