---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

components:
  - ../../../components/networkpolicy-allow-to-api-server
  - ../../../components/networkpolicy-allow-to-coredns
  - ../../../components/networkpolicy-deny-all
images:
  - name: ghcr.io/sdwilsh/nut-shutdown-agent
    newTag: latest@sha256:2a3099a9330cfbd86ba54f5fe86f17bd705122818ad256d4e96b6651777ed918
namespace: nut-shutdown-agent
resources:
  - namespace.yml
  - control-plane
  - networkpolicy/allow-to-nut.yml
  - rbac.yml
  - worker01
  - workers
