---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nut-shutdown-agent
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nut-shutdown-agent-node-manager
rules:
  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - get
      - patch
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - list
  - apiGroups:
      - ""
    resources:
      - pods/eviction
    verbs:
      - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: nut-shutdown-agent-node-manager-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: nut-shutdown-agent-node-manager
subjects:
  - kind: ServiceAccount
    name: nut-shutdown-agent
    namespace: nut-shutdown-agent
