---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

components:
  - ../../../components/jellyfin
  - ../../../components/navidrome
  - ../../../components/networkpolicy-allow-from-traefik
  - ../../../components/networkpolicy-allow-to-coredns
  - ../../../components/networkpolicy-allow-to-internet
  - ../../../components/networkpolicy-allow-to-lldap
  - ../../../components/networkpolicy-allow-within-this-namespace
  - ../../../components/networkpolicy-deny-all
  - ../../../components/tdarr
images:
  - name: jellyfin/jellyfin
    newTag: 10.11.11@sha256:aefb67e6a7ff1debdd154a78a7bbb780fd0c873d8639210a7f6a2016ad2b35db
  - name: deluan/navidrome
    newTag: 0.63.1@sha256:7c43af9f651654e97278be871705aae85a4ee0fa4b310337989699a8ada9b3ed
namespace: aventertainment
patches:
  - path: patches/add_jellyfin_hardware_acc_reqs.yml
    target:
      kind: StatefulSet
      name: jellyfin-statefulset
  - path: patches/add_jellyfin_volumes.yml
    target:
      kind: StatefulSet
      name: jellyfin-statefulset
  - path: patches/add_navidrome_volumes.yml
    target:
      kind: StatefulSet
      name: navidrome-statefulset
  - path: patches/add_tdarr_node_volumes.yml
    target:
      kind: Deployment
      name: tdarr-node-deployment
  - path: patches/add_tdarr_server_volumes.yml
    target:
      kind: StatefulSet
      name: tdarr-server-statefulset
  - path: patches/set_internet_networkpolicy_podselector.yml
    target:
      kind: NetworkPolicy
      name: allow-to-internet-networkpolicy
  - path: patches/set_navidrome_baseurl.yml
    target:
      kind: StatefulSet
      name: navidrome-statefulset
  - path: patches/set_navidrome_disable_star_rating.yml
    target:
      kind: StatefulSet
      name: navidrome-statefulset
  - path: patches/set_navidrome_service_ip.yml
    target:
      kind: Service
      name: navidrome-svc
  - path: patches/set_jellyfin_service_ip.yml
    target:
      kind: Service
      name: jellyfin-svc
  - path: patches/set_tdarr_cache_pvc_size.yml
    target:
      kind: PersistentVolumeClaim
      name: tdarr-cache-pvc
  - path: patches/set_traefik_networkpolicy_pods_and_ports.yml
    target:
      kind: NetworkPolicy
      name: allow-from-traefik-networkpolicy
replacements:
  - source:
      fieldPath: spec.selector
      kind: StatefulSet
      name: jellyfin-statefulset
    targets:
      - fieldPaths:
          - spec.podSelector
        select:
          kind: NetworkPolicy
          name: allow-to-lldap-networkpolicy
resources:
  - namespace.yml
  - ingress.yml
  - networkpolicy/allow-to-jellyfin-from-hfp.yml
  - persistentvolume.yml
  - persistentvolumeclaim.yml
