---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

images:
  - name: jellyfin/jellyfin
    newTag: 10.11.11@sha256:aefb67e6a7ff1debdd154a78a7bbb780fd0c873d8639210a7f6a2016ad2b35db
resources:
  - service.yml
  - statefulset.yml
