---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

images:
  - name: jellyfin/jellyfin
    newTag: 10.11.9@sha256:bc9fa8e1462fffe3d8d4255fc62af478602641f4c0e5f4875fea8563d1189837
resources:
  - service.yml
  - statefulset.yml
