---
apiVersion: keda.sh/v1alpha1
kind: ScaledJob
metadata:
  labels:
    app.kubernetes.io/name: forgejo-runner
  name: this-is-ignored-but-is-required
spec:
  jobTargetRef:
    template:
      spec:
        containers:
          - name: runner
            securityContext:
              runAsGroup: 1001
              runAsNonRoot: true
              runAsUser: 1001
  maxReplicaCount: 9
  pollingInterval: 15
  triggers:
    - type: forgejo-runner
      metadata:
        name: runner
        address: https://code.tswn.us/
        global: "true"
        labels: ci-latest,fedora-latest,node,ubuntu-latest
      authenticationRef:
        name: forgejo-runner-triggerauthentication
