---
apiVersion: keda.sh/v1alpha1
kind: ScaledJob
metadata:
  labels:
    app.kubernetes.io/name: forgejo-runner
  name: this-is-ignored-but-is-required
spec:
  jobTargetRef:
    template:
      spec:
        runtimeClassName: kata-qemu-runtime-rs
        containers:
          - env:
              - name: XDG_CONFIG_HOME
                value: /etc
            name: daemon
            resources:
              limits:
                cpu: 2000m
                memory: 4Gi
              requests:
                cpu: 250m
                memory: 1Gi
            volumeMounts:
              - mountPath: /etc/containers/registries.conf
                name: daemon-config
                readOnly: true
                subPath: registries.conf
              - mountPath: /etc/containers/storage.conf
                name: daemon-config
                readOnly: true
                subPath: storage.conf
              - mountPath: /etc/docker/daemon.json
                name: daemon-config
                readOnly: true
                subPath: daemon.json
              - mountPath: /mnt/scratch
                name: scratch
          - name: runner
            resources:
              limits:
                cpu: 500m
                memory: 1Gi
              requests:
                cpu: 100m
                memory: 256Mi
            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                drop:
                  - ALL
              runAsGroup: 1001
              runAsNonRoot: true
              runAsUser: 1001
        volumes:
          - name: daemon-config
            configMap:
              defaultMode: 0444 # r--r--r--
              name: daemon-config-configmap
          - name: scratch
            emptyDir: {}
  maxReplicaCount: 6
  pollingInterval: 15
  triggers:
    - type: forgejo-runner
      metadata:
        name: runner
        address: https://code.tswn.us/
        global: "true"
        labels: buildah,ci-latest,container,docker,fedora-latest,node,ubuntu-latest
      authenticationRef:
        name: forgejo-runner-triggerauthentication
