---
apiVersion: keda.sh/v1alpha1
kind: ScaledJob
metadata:
  labels:
    app.kubernetes.io/name: forgejo-runner
  name: this-is-ignored-but-is-required
spec:
  jobTargetRef:
    template:
      spec:
        containers:
          - env:
              - name: XDG_CONFIG_HOME
                value: /etc
            name: daemon
            volumeMounts:
              - mountPath: /etc/containers/registries.conf
                name: daemon-config
                readOnly: true
                subPath: registries.conf
              - mountPath: /etc/docker/daemon.json
                name: daemon-config
                readOnly: true
                subPath: daemon.json
          - name: runner
            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                drop:
                  - ALL
              runAsGroup: 1001
              runAsNonRoot: true
              runAsUser: 1001
        volumes:
          - name: daemon-config
            configMap:
              defaultMode: 0444 # r--r--r--
              name: daemon-config-configmap
  maxReplicaCount: 6
  pollingInterval: 15
  triggers:
    - type: forgejo-runner
      metadata:
        name: runner
        address: https://code.tswn.us/
        global: "true"
        labels: ci-latest,docker,fedora-latest,node,ubuntu-latest
      authenticationRef:
        name: forgejo-runner-triggerauthentication
