---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

components:
  - ../../../components/networkpolicy-allow-from-traefik
  - ../../../components/networkpolicy-allow-to-coredns
  - ../../../components/networkpolicy-allow-to-lldap
  - ../../../components/networkpolicy-allow-to-traefik
  - ../../../components/networkpolicy-allow-within-this-namespace
  - ../../../components/networkpolicy-deny-all
  - ../../../components/opencloud
configMapGenerator:
  # These can be set with an environment variable and can therefore just be
  # mounted and pointed to.
  - files:
      - configmap/opencloud/csp.yaml
    name: opencloud-managed-configmap
  # These must be copied into the /config directory in an init container.
  - files:
      - configmap/opencloud/app-registry.yaml
      - configmap/opencloud/apps.yaml
      - configmap/opencloud/banned-passwords-list.txt
      - configmap/opencloud/proxy.yaml
    name: opencloud-copied-configmap
images:
  - name: busybox
    newTag: 1.38.0@sha256:dc2d74b28e4cf8984fa52af1f39bc7c3d9c73760b41a74d629f5d11b1ab28616
  - name: opencloudeu/opencloud-rolling
    newTag: 7.4.0@sha256:e9df43040866c3587daae47af68bc3c412026bc99614686bf6869bdc72c52526
namespace: opencloud
patches:
  - path: patches/opencloud/add_config.yml
    target:
      kind: StatefulSet
      name: opencloud-statefulset
replacements:
  - source:
      fieldPath: spec.template.spec.containers.[name=opencloud].ports.[name=web].name
      kind: StatefulSet
      name: opencloud-statefulset
    targets:
      - fieldPaths:
          - spec.ingress.0.ports.[port=web].port
        select:
          kind: NetworkPolicy
          name: allow-from-traefik-networkpolicy
  - source:
      fieldPath: spec.selector
      kind: StatefulSet
      name: opencloud-statefulset
    targets:
      - fieldPaths:
          - spec.podSelector
        select:
          kind: NetworkPolicy
          name: allow-from-traefik-networkpolicy
      - fieldPaths:
          - spec.podSelector
        select:
          kind: NetworkPolicy
          name: allow-to-lldap-networkpolicy
      - fieldPaths:
          - spec.podSelector
        select:
          kind: NetworkPolicy
          name: allow-to-traefik-networkpolicy
resources:
  - namespace.yml
  - ingress.yml
