---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

components:
  - ../../../components/opencloud
configMapGenerator:
  # These can be set with an environment variable and can therefore just be
  # mounted and pointed to.
  - files:
      - configmap/opencloud/csp.yaml
    name: opencloud-managed-configmap
  # These must be copied into the /config directory in an init container.
  - files:
      - configmap/opencloud/app-registry.yaml
      - configmap/opencloud/apps.yaml
      - configmap/opencloud/banned-passwords-list.txt
      - configmap/opencloud/proxy.yaml
    name: opencloud-copied-configmap
images:
  - name: busybox
    newTag: 1.38.0@sha256:b6762ddf4a50aabb5f4d21aa6f447d05d5633fb09f09c08b33f22356a2f98be0
  - name: opencloudeu/opencloud-rolling
    newTag: 7.1.0@sha256:0bb29038affb1b58655bb8d4fd3dc78b26fb7c0c7e994bda72e6e4e58e6e54b3
namespace: opencloud
patches:
  - path: patches/opencloud/add_config.yml
    target:
      kind: StatefulSet
      name: opencloud-statefulset
resources:
  - namespace.yml
  - ingress.yml
