---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: registry-podmonitor
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: ttl-registry
  podMetricsEndpoints:
    - port: debug
      scheme: http
