---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

images:
  - name: ghcr.io/squat/generic-device-plugin
    # Alas, this is currently not versioned: https://github.com/squat/generic-device-plugin/issues/24
    newTag: latest@sha256:eebecd9172b4c2a61e4b3149c943a4ef2c293d7ceb89b69fec5ce5092eb7cf16
resources:
  - daemonset.yml
