---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

images:
  - name: ghcr.io/squat/generic-device-plugin
    # Alas, this is currently not versioned: https://github.com/squat/generic-device-plugin/issues/24
    newTag: latest@sha256:6a58b2896918e1a4a587d9b39bceec43b3f2e7c85aabdd39f8041add8a7a8585
resources:
  - daemonset.yml
