---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

components:
  - ../../../components/transmission
configMapGenerator:
  - name: protonvpn-configmap
    files:
      - configmap/protonvpn/resolv.conf
  - name: wireguard-scripts-configmap
    files:
      - configmap/scripts/setup_wireguard.sh
images:
  - name: alpine
    newTag: 3.24.0@sha256:a2d49ea686c2adfe3c992e47dc3b5e7fa6e6b5055609400dc2acaeb241c829f4
  - name: dockurr/dnsmasq
    newTag: 2.93@sha256:7ad3c1c802de00d15ef298f2892e4abaf4aa054e2ccc10bf323c000bf393ece5
  - name: lscr.io/linuxserver/transmission
    newTag: 4.0.5-r0-ls223@sha256:bd450da4a328cdf1f89845785150e79b531983b27ab6a1d4c2e3e7dcbf952bfc
namespace: transmission
patches:
  - path: patches/add_downloads_mount.yml
    target:
      kind: StatefulSet
      name: transmission-statefulset
  - path: patches/add_protonvpn.yml
    target:
      kind: StatefulSet
      name: transmission-statefulset
resources:
  - namespace.yml
  - ingress.yml
  - persistentvolume.yml
  - persistentvolumeclaim.yml
