---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: network-ups-tools
  name: nut-svc
spec:
  ports:
    - name: nut
      port: 3493
      protocol: TCP
    - name: metrics
      port: 9199
      protocol: TCP
  selector:
    app.kubernetes.io/name: network-ups-tools
