---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: musicassistant-middleware
spec:
  headers:
    customRequestHeaders:
      X-Forwarded-For: "{clientIP}"
      X-Real-IP: "{clientIP}"
      Host: "{host}"
