---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: stirling-pdf-chart
    version: 2.2.0
    repo: https://docs.stirlingpdf.com/Stirling-PDF-chart/
    releaseName: stirling-pdf
    valuesFile: values.yml
images:
  - name: docker.stirlingpdf.com/stirlingtools/stirling-pdf
    newTag: 2.1.5-fat@sha256:f3f64ba6a71fb4c65d48b78725252bff77cf4f5bfb09da5268e8baeac696e888 
namespace: stirling-pdf
resources:
  - namespace.yml
