---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: stirling-pdf-chart
    version: 1.9.1
    repo: https://docs.stirlingpdf.com/Stirling-PDF-chart/
    releaseName: stirling-pdf
    valuesFile: values.yml
images:
  - name: docker.stirlingpdf.com/stirlingtools/stirling-pdf
    newTag: 0.46.1-fat@sha256:64e4064e9ad57ee61921cc8a2587c7354f7e9cb05f123b1067227bc19dac5964 
namespace: stirling-pdf
resources:
  - namespace.yml
