---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: stirling-pdf-chart
    version: 2.2.0
    repo: https://docs.stirlingpdf.com/Stirling-PDF-chart/
    releaseName: stirling-pdf
    valuesFile: values.yml
images:
  - name: docker.stirlingpdf.com/stirlingtools/stirling-pdf
    newTag: 2.4.5-fat@sha256:25c0192c746aa6d263b43b96bfa82baecc8d429a27de788241d5dc76c8d345c8 
namespace: stirling-pdf
resources:
  - namespace.yml
