FROM docker.io/grafana/alloy:v1.11.1@sha256:422454f72cdbd7586358ae6bf7c55818281d48ca16eeba4ad4d665e60e5e046e

# This exists only due to the lack of curl in the Alloy container:
# https://github.com/grafana/alloy/issues/477
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        curl \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*
