FROM docker.io/grafana/alloy:v1.11.0@sha256:e849f170152aff2015427908463a08c48416abade66302cd880379609058042b

# This exists only due to the lack of curl in the Alloy container:
# https://github.com/grafana/alloy/issues/477
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        curl \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*
