---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: forgejo-runner-dns

components:
  - ../../../components/coredns
  - ../../../components/networkpolicy-allow-coredns-to-internet
  - ../../../components/networkpolicy-deny-all
  - ../../../components/pod-security-enforce-restricted
configMapGenerator:
  - name: forgejo-runner-dns-configmap
    files:
      - configmap/coredns/Corefile
generatorOptions:
  annotations:
    argocd.argoproj.io/sync-options: Prune=true
  labels:
    app.kubernetes.io/name: coredns
images:
  - name: docker.io/coredns/coredns
    newTag: 1.14.7@sha256:7efd3c635b03efd68c4e8398fc45f0d993d0e9ab016f72c1cefb0fd6d01aa286
patches:
  - path: patches/coredns/mount_configuration.yml
    target:
      kind: Deployment
      name: coredns-deployment
resources:
  - namespace.yml
