---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: forgejo-runner-dns

components:
  - ../../../components/coredns
  - ../../../components/networkpolicy-allow-coredns-to-internet
  - ../../../components/networkpolicy-deny-all
  - ../../../components/pod-security-enforce-restricted
configMapGenerator:
  - name: forgejo-runner-dns-configmap
    files:
      - configmap/coredns/Corefile
generatorOptions:
  annotations:
    argocd.argoproj.io/sync-options: Prune=true
  labels:
    app.kubernetes.io/name: coredns
images:
  - name: docker.io/coredns/coredns
    newTag: 1.13.2@sha256:94caebb89dcfb9d2c4be45bfda34410a3e1092458fbbbc0284365c9e4c9a7818
patches:
  - path: patches/coredns/mount_configuration.yml
    target:
      kind: Deployment
      name: coredns-deployment
resources:
  - namespace.yml
