---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-within-this-namespace-networkpolicy
spec:
  egress:
    - to:
        - podSelector: {}
  ingress:
    - from:
        - podSelector: {}
  podSelector:
    matchLabels:
  policyTypes:
    - Egress
    - Ingress
