---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

components:
  - ../../../components/immich
images:
  - name: ghcr.io/immich-app/immich-server
    newTag: v1.134.0@sha256:073fc04c7e3d18ace466c20763809cf17aa55765ed610f12971b392a6a80b50c
  - name: ghcr.io/immich-app/immich-machine-learning
    newTag: v1.134.0@sha256:e157e0fa0d4363b0b6bab1923adab5951bbcdb71cd9016470bc6810dae21d115
namespace: immich
patches:
  - path: patches/add_postgres.yml
    target:
      kind: Deployment
      name: immich-server
resources:
  - namespace.yml
  - ingress.yml
  - postgresql.yml
