---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

components:
  - ../../../components/cnpg-backup
  - ../../../components/immich
images:
  - name: ghcr.io/immich-app/immich-server
    newTag: v2.6.1@sha256:aa7fe8eec3130742d07498dac7e02baa2d32a903573810ba95ed11f155c7eac1
  - name: ghcr.io/immich-app/immich-machine-learning
    newTag: v2.6.1@sha256:cafc1ff51b95a931d17d69226435bbb28ea314f151598b8b087391c232d00ab6
  - name: postgres
    newTag: 18@sha256:5773fe724c49c42a7a9ca70202e11e1dff21fb7235b335a73f39297d200b73a2
namespace: immich
patches:
  # cnpg
  - path: patches/cnpg/set_backup_path.yml
    target:
      kind: ObjectStore
      name: garage-objectstore
  # immich
  - path: patches/add_postgres.yml
    target:
      kind: Deployment
      name: immich-server
resources:
  - namespace.yml
  - cnpg/cluster.yml
  - cnpg/podmonitor.yml
  - cnpg/scheduledbackup.yml
  - ingress.yml
