---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

components:
  - ../../../components/immich
images:
  - name: ghcr.io/immich-app/immich-server
    newTag: v1.123.0@sha256:666ce77995230ff7327da5d285c861895576977237de08564e3c3ddf842877eb
  - name: ghcr.io/immich-app/immich-machine-learning
    newTag: v1.123.0@sha256:fca90362ff3081fc7762d731eb24de262181eaec28afc51eff1d3ca5348663cd
namespace: immich
resources:
  - namespace.yml
  - ingress.yml
