---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    hogs.tswn.us/prometheus-target: "true"
    hogs.tswn.us/traefik-client: "true"
    hogs.tswn.us/traefik-route: "true"
  name: this-is-ignored-but-is-required
