---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-to-mcp-servers-networkpolicy
spec:
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              hogs.tswn.us/bifrost-route: "true"
          podSelector:
            matchLabels:
              hogs.tswn.us/bifrost-route: "true"
      ports:
        - port: web
          protocol: TCP
  podSelector:
    matchLabels:
      app.kubernetes.io/name: bifrost
  policyTypes:
    - Egress
