---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

images:
  - name: ghcr.io/haveagitgat/tdarr
    newTag: 2.84.01@sha256:93dd407f8a28b035b3ebece794bd3f489a9b07a810ca02b804adf72387888355
  - name: ghcr.io/haveagitgat/tdarr_node
    newTag: 2.84.01@sha256:9d8d3a24c88cc0ff2121565bb774ddd082694be3b6fb7cc0b5c9391e2c550db9
resources:
  - deployment.yml
  - service.yml
  - statefulset.yml
