---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

images:
  - name: ghcr.io/haveagitgat/tdarr
    newTag: 2.74.01@sha256:4dd21e8aa92f10601c35828566ddaadbb6d9d4335d004411ee69f1e02714d1c8
  - name: ghcr.io/haveagitgat/tdarr_node
    newTag: 2.74.01@sha256:1dd3efb3fdb3d29a3aa115bfd0d6a29e87168b44b42614f526dfd9c73410cb5e
resources:
  - deployment.yml
  - service.yml
  - statefulset.yml
