FROM ghcr.io/tensorchord/cloudnative-vectorchord:17-0.5.3@sha256:ef3bf2e3abe76c3939b994afbde46cb9f24d2fbdf7ff2026a03aefa84d9a2a23

USER root

RUN --mount=type=cache,dst=/var/cache \
    --mount=type=cache,dst=/var/log \
    --mount=type=tmpfs,dst=/tmp \
  set -xe \
  && apt-get update \
  && apt-get install -y --no-install-recommends \
    build-essential \
    clang \
    git \
    llvm \
    postgresql-server-dev-17 \
  && git clone -b REL4_2_0 https://github.com/pgaudit/set_user.git /tmp/set_user \
  && make -C /tmp/set_user USE_PGXS=1 \
  && make -C /tmp/set_user USE_PGXS=1 install \
  && apt-get purge -y \
    build-essential \
    clang \
    git \
    llvm \
    postgresql-server-dev-17 \
  && apt-get autopurge -y \
  && apt-get install -y --no-install-recommends \
    postgresql-17-pg-stat-kcache \
  && rm -fr /tmp/* \
  && rm -rf /var/lib/apt/lists/*

USER 26