---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

images:
  - name: dxflrs/garage
    newTag: v2.4.1@sha256:9c96caa2612d3411acc5b0e6701fb238dbfba33e533a6d7d3d811a4b12d0d020
resources:
  - daemonset.yml
  - rbac.yml
  - service/garage-metrics.yml
  - service/garage.yml
  - servicemonitor.yml

