---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

images:
  - name: dxflrs/garage
    newTag: v2.3.0@sha256:866bd13ed2038ba7e7190e840482bc27234c4afaf77be8cfa439ae088c1e4690
resources:
  - daemonset.yml
  - rbac.yml
  - service/garage-metrics.yml
  - service/garage.yml
  - servicemonitor.yml

