---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - name: cnpg-scripts-configmap
    files:
      - configmap/restart-cnpg-if-needed.sh
images:
  - name: docker.io/bitnami/kubectl
    newTag: latest@sha256:558420daf32bbc382e3e9af4537f4073085b336ddd47399a3b70e70087115978
namespace: cnpg-system
patches:
  - patch: |-
      ---
      apiVersion: v1
      kind: Namespace
      metadata:
        labels:
          pod-security.kubernetes.io/enforce: restricted
          pod-security.kubernetes.io/enforce-version: latest
        name: this-is-ignored-but-is-required
    target:
      kind: Namespace
resources:
  - https://raw.githubusercontent.com/cloudnative-pg/cloudnative-pg/main/releases/cnpg-1.28.4.yaml
  - https://github.com/cloudnative-pg/plugin-barman-cloud/releases/download/v0.13.0/manifest.yaml
  - configmap.yml
  - job.yml
  - podmonitor.yml
  - rbac.yml
  - storageclass/data.yml
  - storageclass/legacy.yml
  - storageclass/wal.yml
