---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

components:
  - ../../../components/schedule-prefer-control-plane
configMapGenerator:
  - name: cnpg-scripts-configmap
    files:
      - configmap/restart-cnpg-if-needed.sh
images:
  - name: docker.io/bitnami/kubectl
    newTag: latest@sha256:999d5eb28f404b45f15117f2a110ff23c6164f76edac261d75d783b6e88252b7
namespace: cnpg-system
patches:
  - patch: |-
      ---
      apiVersion: v1
      kind: Namespace
      metadata:
        labels:
          pod-security.kubernetes.io/enforce: restricted
          pod-security.kubernetes.io/enforce-version: latest
        name: this-is-ignored-but-is-required
    target:
      kind: Namespace
resources:
  - https://raw.githubusercontent.com/cloudnative-pg/cloudnative-pg/main/releases/cnpg-1.30.1.yaml
  - https://github.com/cloudnative-pg/plugin-barman-cloud/releases/download/v0.15.1/manifest.yaml
  - configmap.yml
  - job.yml
  - podmonitor.yml
  - rbac.yml
  - storageclass/data.yml
  - storageclass/legacy.yml
  - storageclass/wal.yml
