---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

components:
  - https://github.com/marinatedconcrete/config/kustomization/components/factorio?ref=kustomize-factorio@v0.1.3
  - ../../../components/networkpolicy-allow-to-coredns
  - ../../../components/networkpolicy-allow-within-this-namespace
  - ../../../components/networkpolicy-deny-all
  - ../../../components/pod-security-enforce-baseline
namespace: factorio-relic
patches:
  - path: patches/set_load_balancer.yml
    target:
      kind: Service
      name: factorio-game-svc
  - path: patches/use_user_namespace.yml
    target:
      kind: StatefulSet
      name: factorio-statefulset
resources:
  - namespace.yml
  - ingress.yml
  - networkpolicy/allow-from-factorio-to-internet.yml
  - networkpolicy/allow-to-admin-from-traefik.yml
  - networkpolicy/allow-to-game-from-choros.yml
