---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

configMapGenerator:
  - name: containers-config-configmap
    files:
      - registries.conf
      - storage.conf

configurations:
  - namereference.yml
