---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: immich-pg-cluster
spec:
  backup:
    target: primary
  bootstrap:
    initdb:
      database: immich
      dataChecksums: true
      owner: immich
      postInitApplicationSQL:
        - CREATE EXTENSION IF NOT EXISTS vchord CASCADE;
  env:
    - name: TZ
      value: America/Los_Angeles
  imageName: ghcr.io/cloudnative-pg/postgresql:18-system-bookworm@sha256:61bcf7237cb5363ff84ac357bdf66a29d1220f88fc05e64473d7824043e4b150
  instances: 3
  managed:
    services:
      disabledDefaultServices:
        - r
        - ro
  monitoring:
    tls:
      enabled: true
  plugins:
    - enabled: true
      isWALArchiver: true
      name: barman-cloud.cloudnative-pg.io
      parameters:
        barmanObjectName: garage-objectstore
  postgresql:
    extensions:
      - dynamic_library_path:
          - /usr/lib/postgresql/18/lib/
        extension_control_path:
          - /usr/share/postgresql/18/
        image:
          reference: ghcr.io/tensorchord/vchord-scratch:pg18-v1.1.1@sha256:bdea43bed2a414e21bbf71767bf6f0739747ac480b267b51772dc214ac28dcb3
        name: vchord
    shared_preload_libraries:
      - vchord
    synchronous:
      failoverQuorum: true
      method: any
      number: 1
  primaryUpdateMethod: switchover
  primaryUpdateStrategy: unsupervised
  priorityClassName: critical-application-infra
  storage:
    size: 5Gi
    storageClass: cnpg-data-encrypted-storage
  walStorage:
    size: 4Gi
    storageClass: cnpg-wal-encrypted-storage
