---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: immich-pg-database
spec:
  name: immich
  owner: immich
  cluster:
    name: immich-pg-cluster
  extensions:
    - ensure: present
      name: cube
    - ensure: present
      name: earthdistance
    - ensure: present
      name: pg_trgm
    - ensure: present
      name: unaccent
    - ensure: present
      name: uuid-ossp
    - ensure: present
      name: vchord
    - ensure: present
      name: vector
