---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

# This component holds one model server.  The overlay includes it one time
# for each model that it runs.  Give each instance a `namePrefix` and a
# patch that sets the model.
configMapGenerator:
  - name: local-llm-scripts-configmap
    files:
      - configmap/fetch-model.sh
resources:
  - service.yml
  - statefulset.yml
