FROM alpine:3.24.1@sha256:28bd5fe8b56d1bd048e5babf5b10710ebe0bae67db86916198a6eec434943f8b AS builder

# hadolint ignore=DL3018
RUN apk add --no-cache \
    ca-certificates \
    curl

# Download and Install kubectl
# renovate: datasource=github-releases depName=kubernetes/kubernetes
ARG KUBECTL_VERSION=v1.36.4
RUN curl -o /usr/local/bin/kubectl \
    -f \
    -L \
    "https://dl.k8s.io/release/${KUBECTL_VERSION}/bin/linux/amd64/kubectl" \
  && chmod +x /usr/local/bin/kubectl

FROM alpine:3.24.1@sha256:28bd5fe8b56d1bd048e5babf5b10710ebe0bae67db86916198a6eec434943f8b

# hadolint ignore=DL3018
RUN apk add --no-cache \
    nut \
    util-linux

COPY --from=builder /usr/local/bin/kubectl /usr/local/bin/kubectl
COPY monitor.sh shutdown.sh /
RUN chmod +x /monitor.sh /shutdown.sh

ENTRYPOINT ["/monitor.sh"]
