FROM alpine:3.24.2@sha256:294b683cb724975bec92580e1e685676bd4b50bda910ddb8c51d4cabeaec77e6 AS builder

# hadolint ignore=DL3018
RUN apk add --no-cache \
    ca-certificates \
    curl

# Download and Install kubectl
# renovate: datasource=github-releases depName=kubernetes/kubernetes
ARG KUBECTL_VERSION=v1.36.5
RUN curl -o /usr/local/bin/kubectl \
    -f \
    -L \
    "https://dl.k8s.io/release/${KUBECTL_VERSION}/bin/linux/amd64/kubectl" \
  && chmod +x /usr/local/bin/kubectl

FROM alpine:3.24.2@sha256:294b683cb724975bec92580e1e685676bd4b50bda910ddb8c51d4cabeaec77e6

# hadolint ignore=DL3018
RUN apk add --no-cache \
    nut \
    util-linux

COPY --from=builder /usr/local/bin/kubectl /usr/local/bin/kubectl
COPY monitor.sh shutdown.sh /
RUN chmod +x /monitor.sh /shutdown.sh

ENTRYPOINT ["/monitor.sh"]
