---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - name: alloy-config
    files:
      - configmap/journal.alloy
      - configmap/loki.alloy
      - configmap/networkpolicy.alloy
  - name: alloy-scripts-configmap
    files:
      - configmap/install_journald_conf.sh
      - configmap/logger_sidecar.py
helmCharts:
  - name: alloy
    version: 1.13.0
    repo: https://grafana.github.io/helm-charts
    releaseName: alloy
    valuesFile: alloy-values.yml
  - name: prometheus-node-exporter
    version: 4.59.0
    repo: https://prometheus-community.github.io/helm-charts
    releaseName: node-exporter
    valuesFile: node-exporter-values.yml
  - name: prometheus-smartctl-exporter
    version: 0.17.1
    repo: https://prometheus-community.github.io/helm-charts
    releaseName: smartctl-exporter
    valuesFile: smartctl-exporter-values.yml
images:
  - name: docker.io/grafana/alloy
    newTag: v1.20.1@sha256:2aa2099af76c0098d4af7a4d6e48f86cb66dc1a000222ad927a1c67c6542d13f
  - name: quay.io/prometheus-operator/prometheus-config-reloader
    newTag: v0.94.1@sha256:06b52bd4dbe3ed6dd5905aadaf8b9987d9da4c31d37bb86deaadae68cee2d26b
  - name: quay.io/prometheus/node-exporter
    newTag: v1.12.1@sha256:1b4e4438faca4dd7e001dd445d161a4a2091b0fededa84093b3a8dfeae1f1be0
  - name: quay.io/prometheuscommunity/smartctl-exporter
    newTag: v0.15.0@sha256:a76e08dbf5db4781fefd1ed81c65ad46ae8d2849dae6b6d3acebcde2fc4e59d6
namespace: node-monitoring
resources:
  - namespace.yml
  - rbac.yml
