---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - name: alloy-config
    files:
      - configmap/journal.alloy
      - configmap/loki.alloy
  - name: alloy-scripts-configmap
    files:
      - configmap/install_journald_conf.sh
helmCharts:
  - name: alloy
    version: 1.6.2
    repo: https://grafana.github.io/helm-charts
    releaseName: alloy
    valuesFile: alloy-values.yml
  - name: prometheus-node-exporter
    version: 4.52.2
    repo: https://prometheus-community.github.io/helm-charts
    releaseName: node-exporter
    valuesFile: node-exporter-values.yml
images:
  - name: docker.io/grafana/alloy
    newTag: v1.14.2@sha256:eadfe35ea52b26cbec4d4d780fbcc31edb31108c1c9e537ca59557a5a102c712
  - name: ghcr.io/jimmidyson/configmap-reload
    newTag: v0.15.0@sha256:b578b7599d65c0279f6e1aad201bba737b9b15e6a4f308281d9e26f765e6657f 
  - name: quay.io/prometheus/node-exporter
    newTag: v1.11.1@sha256:0f422f62c15f154af8d8572b23d623aebfb10cec73a5c654d18f911f3f9df241
namespace: node-monitoring
resources:
  - namespace.yml
