---
namespaceOverride: node-monitoring

prometheus:
  monitor:
    enabled: true
    relabelings:
      - action: replace
        sourceLabels: [__meta_kubernetes_endpoint_node_name]
        targetLabel: node
