---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

components:
  - ../../../components/networkpolicy-allow-to-coredns
  - ../../../components/networkpolicy-allow-to-loki
  - ../../../components/networkpolicy-deny-all
  - ../../../components/pod-security-enforce-restricted
configMapGenerator:
  - name: alloy-config
    files:
      - configmap/loki.alloy
      - configmap/syslog.alloy
helmCharts:
  - name: alloy
    version: 1.12.1
    repo: https://grafana.github.io/helm-charts
    releaseName: alloy
    valuesFile: alloy-values.yml
images:
  - name: docker.io/grafana/alloy
    newTag: v1.20.0@sha256:f111cce835516c5f99166342be7038496b52ced16667be5a11e19258a3e4cd30
namespace: unifi-syslog
patches:
  - path: patches/add_loki_client_label.yml
    target:
      kind: Deployment
      name: alloy
resources:
  - namespace.yml
  - networkpolicy/allow-from-unifi-devices.yml
  - service.yml
