---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

components:
  - ../../../components/networkpolicy-allow-to-coredns
  - ../../../components/networkpolicy-allow-to-loki
  - ../../../components/networkpolicy-deny-all
  - ../../../components/pod-security-enforce-restricted
configMapGenerator:
  - name: alloy-config
    files:
      - configmap/loki.alloy
      - configmap/syslog.alloy
helmCharts:
  - name: alloy
    version: 1.13.1
    repo: https://grafana.github.io/helm-charts
    releaseName: alloy
    valuesFile: alloy-values.yml
images:
  - name: docker.io/grafana/alloy
    newTag: v1.20.1@sha256:2aa2099af76c0098d4af7a4d6e48f86cb66dc1a000222ad927a1c67c6542d13f
namespace: unifi-syslog
patches:
  - path: patches/add_loki_client_label.yml
    target:
      kind: Deployment
      name: alloy
resources:
  - namespace.yml
  - networkpolicy/allow-from-unifi-devices.yml
  - service.yml
