---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kube-vip.io/loadbalancerIPs: 10.11.1.2
  name: unifi-syslog-svc
spec:
  externalTrafficPolicy: Local
  ports:
    - name: syslog
      port: 514
      protocol: UDP
      targetPort: syslog
  selector:
    app.kubernetes.io/instance: alloy
    app.kubernetes.io/name: alloy
  type: LoadBalancer
