---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

components:
  - ../../../components/cnpg-backup
  - ../../../components/networkpolicy-allow-from-cnpg-operator
  - ../../../components/networkpolicy-allow-from-prometheus-to-cnpg-cluster
  - ../../../components/networkpolicy-allow-from-traefik
  - ../../../components/networkpolicy-allow-to-coredns
  - ../../../components/networkpolicy-allow-to-garage
  - ../../../components/networkpolicy-allow-to-internet
  - ../../../components/networkpolicy-allow-to-traefik
  - ../../../components/networkpolicy-allow-within-this-namespace
  - ../../../components/networkpolicy-deny-all
helmCharts:
  - name: manyfold
    version: 1.0.3
    repo: https://charts.jeffresc.dev
    releaseName: manyfold
    valuesFile: values.yml
images:
  - name: busybox
    newTag: 1.38.0@sha256:dc2d74b28e4cf8984fa52af1f39bc7c3d9c73760b41a74d629f5d11b1ab28616
  - name: ghcr.io/manyfold3d/manyfold
    newTag: 0.147.2@sha256:54b7f4e95f8a858d63c7b532ed18b41f2ba5baa36e39371c6f240fdad943379a
namespace: manyfold
patches:
  - path: patches/harden_deployment.yml
    target:
      kind: Deployment
      name: manyfold
  - patch: |-
      $patch: delete
      apiVersion: v1
      kind: Pod
      metadata:
        name: manyfold-test-connection
    target:
      kind: Pod
      name: manyfold-test-connection
  - path: patches/cnpg/set_backup_path.yml
    target:
      kind: ObjectStore
      name: garage-objectstore
replacements:
  - source:
      fieldPath: spec.template.spec.containers.[name=manyfold].ports.[name=http].name
      kind: Deployment
      name: manyfold
    targets:
      - fieldPaths:
          - spec.ingress.0.ports.[port=web].port
        select:
          kind: NetworkPolicy
          name: allow-from-traefik-networkpolicy
  - source:
      fieldPath: spec.selector
      kind: Deployment
      name: manyfold
    targets:
      - fieldPaths:
          - spec.podSelector
        select:
          kind: NetworkPolicy
          name: allow-from-traefik-networkpolicy
      - fieldPaths:
          - spec.podSelector
        select:
          kind: NetworkPolicy
          name: allow-to-internet-networkpolicy
      - fieldPaths:
          - spec.podSelector
        select:
          kind: NetworkPolicy
          name: allow-to-traefik-networkpolicy
resources:
  - namespace.yml
  - cnpg/backup.yml
  - cnpg/cluster.yml
  - cnpg/podmonitor.yml
  - cnpg/scheduledbackup.yml
  - redis.yml
