---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

components:
  - ../../../components/manyfold
images:
  - name: busybox
    newTag: 1.37.0@sha256:1487d0af5f52b4ba31c7e465126ee2123fe3f2305d638e7827681e7cf6c83d5e
  - name: ghcr.io/manyfold3d/manyfold-solo
    newTag: 0.140.1@sha256:b9b12a64a86319c729a592654d5831954897e39152f5ff12ad2773ff6ddd8e7b
namespace: manyfold
resources:
  - namespace.yml
  - ingress.yml
