---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

images:
  - name: deluan/navidrome
    newTag: 0.63.2@sha256:9012939114fbb1bb641b81cf96dec5ded15f0aafefe8d47a511d7cb919658e40
resources:
  - service.yml
  - statefulset.yml
