---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

images:
  - name: deluan/navidrome
    newTag: 0.64.2@sha256:38dc2727bfcfd5ede290f8ada114fc90368146f265ae4701ddddbcbe2a44ee52
resources:
  - service.yml
  - statefulset.yml
