# renovate: datasource=docker depName=python
ARG PYTHON_VERSION=3.13

FROM ghcr.io/hadolint/hadolint:v2.14.0@sha256:27086352fd5e1907ea2b934eb1023f217c5ae087992eb59fde121dce9c9ff21e AS hadolint
FROM registry.k8s.io/kustomize/kustomize:v5.7.1@sha256:937e7832dc0b09288b1398399dadb97382a27bbc35bee8fdcac47c7de4fff14d AS kustomize
FROM koalaman/shellcheck:stable@sha256:bb596a0d169b85ddd81d8b6d3a2ff6d5baf5fca10b97f575ebc647c3dff62b3d AS shellcheck

FROM mcr.microsoft.com/devcontainers/python:1-${PYTHON_VERSION}

COPY --chmod=777 --from=hadolint /bin/hadolint /usr/local/bin/hadolint
COPY --chmod=777 --from=kustomize /app/kustomize /usr/local/bin/kustomize
COPY --chmod=777 --from=shellcheck /bin/shellcheck /usr/local/bin/shellcheck

# Download and Install longhorncli
# renovate: datasource=github-releases depName=longhorn/cli
ARG LONGHORN_CLI_VERSION=v1.9.2
RUN curl -o /usr/local/bin/longhorncli \
    -L \
    https://github.com/longhorn/cli/releases/download/${LONGHORN_CLI_VERSION}/longhornctl-linux-amd64 \
  && chmod +x /usr/local/bin/longhorncli

# Setup and Configure OpenPubkey SSH
# renovate: datasource=github-releases depName=openpubkey/opkssh
ARG OPKSSH_VERSION=0.10.0
RUN --mount=type=cache,dst=/deb \
  curl -o /deb/opkssh.deb \
    -L \
    https://github.com/openpubkey/opkssh/releases/download/v${OPKSSH_VERSION}/opkssh_${OPKSSH_VERSION}_linux_amd64.deb

RUN --mount=type=cache,dst=/deb \
  apt-get update \
  && apt-get install -y --no-install-recommends \
    /deb/opkssh.deb \
    dnsutils \
    iproute2 \
    iputils-ping \
    libssh-dev \
    vim \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*

WORKDIR /tmp
COPY requirements.txt requirements.txt
RUN pip3 install --no-cache-dir -r requirements.txt
