# renovate: datasource=docker depName=python
ARG PYTHON_VERSION=3.13

FROM ghcr.io/hadolint/hadolint:v2.12.0@sha256:30a8fd2e785ab6176eed53f74769e04f125afb2f74a6c52aef7d463583b6d45e AS hadolint
FROM koalaman/shellcheck:stable@sha256:bb596a0d169b85ddd81d8b6d3a2ff6d5baf5fca10b97f575ebc647c3dff62b3d AS shellcheck

FROM mcr.microsoft.com/devcontainers/python:1-${PYTHON_VERSION}

COPY --chmod=777 --from=hadolint /bin/hadolint /usr/local/bin/hadolint
COPY --chmod=777 --from=shellcheck /bin/shellcheck /usr/local/bin/shellcheck

# Setup and Configure OpenPubkey SSH
# renovate: datasource=github-releases depName=openpubkey/opkssh
ARG OPKSSH_VERSION=0.8.0
RUN --mount=type=cache,dst=/deb \
  curl -o /deb/opkssh.deb \
    -L \
    https://github.com/openpubkey/opkssh/releases/download/v${OPKSSH_VERSION}/opkssh_${OPKSSH_VERSION}_linux_amd64.deb

RUN --mount=type=cache,dst=/deb \
  apt-get update \
  && apt-get install -y --no-install-recommends \
    /deb/opkssh.deb \
    dnsutils \
    iproute2 \
    iputils-ping \
    libssh-dev \
    vim \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*

WORKDIR /tmp
COPY requirements.txt requirements.txt
RUN pip3 install --no-cache-dir -r requirements.txt
