FROM ghcr.io/hadolint/hadolint:v2.14.0@sha256:27086352fd5e1907ea2b934eb1023f217c5ae087992eb59fde121dce9c9ff21e AS hadolint
FROM registry.k8s.io/kustomize/kustomize:v5.8.0@sha256:98424842862ed35fa666dbaac02159623567e1e9e184d91382fa665e89023258 AS kustomize
FROM koalaman/shellcheck:stable@sha256:bb596a0d169b85ddd81d8b6d3a2ff6d5baf5fca10b97f575ebc647c3dff62b3d AS shellcheck

FROM mcr.microsoft.com/devcontainers/python:3-3@sha256:77238990f09e14b9baecb21c620bb919a6293fdb7a539d19f53996860b47a00a

COPY --chmod=777 --from=hadolint /bin/hadolint /usr/local/bin/hadolint
COPY --chmod=777 --from=kustomize /app/kustomize /usr/local/bin/kustomize
COPY --chmod=777 --from=shellcheck /bin/shellcheck /usr/local/bin/shellcheck

# Download and Install garage CLI
# renovate: datasource=git-tags registryUrl=https://git.deuxfleurs.fr/Deuxfleurs/garage
ARG GARAGE_CLI_VERSION=v2.1.0
RUN curl -o /usr/local/bin/garage \
    -L \
    https://garagehq.deuxfleurs.fr/_releases/${GARAGE_CLI_VERSION}/x86_64-unknown-linux-musl/garage \
  && chmod +x /usr/local/bin/garage

# Download and Install longhorncli
# renovate: datasource=github-releases depName=longhorn/cli
ARG LONGHORN_CLI_VERSION=v1.10.1
RUN curl -o /usr/local/bin/longhorncli \
    -L \
    https://github.com/longhorn/cli/releases/download/${LONGHORN_CLI_VERSION}/longhornctl-linux-amd64 \
  && chmod +x /usr/local/bin/longhorncli

# Download and Setup CloudnativePG kubectl Plugin
# renovate: datasource=github-releases depName=cloudnative-pg/cloudnative-pg
ARG CNPG_VERSION=1.28.0
RUN --mount=type=cache,dst=/deb \
  curl -o /deb/kubectl-cnpg.deb \
    -L \
    https://github.com/cloudnative-pg/cloudnative-pg/releases/download/v${CNPG_VERSION}/kubectl-cnpg_${CNPG_VERSION}_linux_x86_64.deb

# https://cloudnative-pg.io/docs/1.28/kubectl-plugin/#configuring-auto-completion
RUN <<EOF cat > /usr/local/bin/kubectl_complete-cnpg
#!/usr/bin/env sh

# Call the __complete command passing it all arguments
kubectl cnpg __complete "\$@"
EOF

RUN chmod +x /usr/local/bin/kubectl_complete-cnpg

# Setup and Configure OpenPubkey SSH
# renovate: datasource=github-releases depName=openpubkey/opkssh
ARG OPKSSH_VERSION=0.10.0
RUN --mount=type=cache,dst=/deb \
  curl -o /deb/opkssh.deb \
    -L \
    https://github.com/openpubkey/opkssh/releases/download/v${OPKSSH_VERSION}/opkssh_${OPKSSH_VERSION}_linux_amd64.deb

RUN --mount=type=cache,dst=/deb \
  apt-get update \
  && apt-get install -y --no-install-recommends \
    /deb/kubectl-cnpg.deb \
    /deb/opkssh.deb \
    dnsutils \
    iproute2 \
    iputils-ping \
    libssh-dev \
    vim \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*

WORKDIR /tmp
COPY requirements.txt requirements.txt
RUN pip3 install --no-cache-dir -r requirements.txt
