# Allow build scripts to be referenced without being copied into the final image.
FROM scratch AS ctx
COPY build_files /

# This is the base image.
FROM quay.io/fedora/fedora-bootc:43@sha256:518542ce6aaab657f1ede2a9188c15e2a20052fa0b78d64a974a9c51aef6abe2

ARG TARGETPLATFORM

RUN --mount=type=bind,from=ctx,source=/,target=/ctx \
    --mount=type=cache,dst=/var/cache \
    --mount=type=cache,dst=/var/log \
    --mount=type=tmpfs,dst=/tmp \
    /ctx/build.sh && \
    ostree container commit

# Verify final image and contents are correct.
RUN bootc container lint
