# Allow build scripts to be referenced without being copied into the final image.
FROM scratch AS ctx
COPY build_files /

# This is the base image.
FROM quay.io/fedora/fedora-bootc:42@sha256:2d517230f5913d3d70d92ab49a1bf5a39307b4a93fc3589adaf98f41735cbc7f

ARG TARGETPLATFORM

RUN --mount=type=bind,from=ctx,source=/,target=/ctx \
    --mount=type=cache,dst=/var/cache \
    --mount=type=cache,dst=/var/log \
    --mount=type=tmpfs,dst=/tmp \
    /ctx/build.sh && \
    ostree container commit

# Verify final image and contents are correct.
RUN bootc container lint
