# Allow build scripts to be referenced without being copied into the final image.
FROM scratch AS ctx
COPY build_files /

# This is the base image.
FROM quay.io/fedora/fedora-bootc:42@sha256:8a9f80273d499de2ddc4dff445a3ab4a296ef0d0f21399e7a36ef42f62c63b23

ARG TARGETPLATFORM

RUN --mount=type=bind,from=ctx,source=/,target=/ctx \
    --mount=type=cache,dst=/var/cache \
    --mount=type=cache,dst=/var/log \
    --mount=type=tmpfs,dst=/tmp \
    /ctx/build.sh && \
    ostree container commit

# Verify final image and contents are correct.
RUN bootc container lint
