---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

components:
  - https://github.com/marinatedconcrete/config/kustomization/components/paperless?ref=kustomize-paperless@v1.2.0
configMapGenerator:
  - name: paperless-backup-scripts-configmap
    files:
      - configmap/scripts/backup.sh
images:
  - name: docker.io/apache/tika
    newTag: 3.3.0.0@sha256:2a565f1ea1290bdcb74a7d35957d16a989ed44ef98790dcdcc28121d728fa583
  - name: gotenberg/gotenberg
    newTag: 8.32.0@sha256:a40c5a46b79d812ce2f5e139278163142a054050bfd1e5f162da36d3d11c7138
patches:
  - path: patches/add_tika.yml
    target:
      kind: StatefulSet
      name: paperless
  - path: patches/mount_memory_tmp.yml
    target:
      kind: StatefulSet
      name: paperless
  - path: patches/pin_pvc_paperless-media.yml
    target:
      kind: PersistentVolumeClaim
      name: paperless-media
resources:
  - clusterrole.yaml
  - clusterrolebinding.yaml
  - cronjob.yml
  - persistentvolume.yml
  - pvc.yml
  - serviceaccount.yml
