---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

components:
  - https://github.com/marinatedconcrete/config/kustomization/components/paperless?ref=kustomize-paperless@v1.2.0
configMapGenerator:
  - name: paperless-backup-scripts-configmap
    files:
      - configmap/scripts/backup.sh
images:
  - name: docker.io/apache/tika
    newTag: 3.3.1.0@sha256:90b7fa1dc018434075fce9e1d9b88b1e3d0ea6979d0cf86e116c79a8073ae973
  - name: gotenberg/gotenberg
    newTag: 8.34.0@sha256:67097317623a503ba2a6a7e9ae8db6929a1f7e1bbd88077bacf2d325fbdab923
patches:
  - path: patches/add_tika.yml
    target:
      kind: StatefulSet
      name: paperless
  - path: patches/mount_memory_tmp.yml
    target:
      kind: StatefulSet
      name: paperless
  - path: patches/name_port.yml
    target:
      kind: StatefulSet
      name: paperless
  - path: patches/pin_pvc_paperless-media.yml
    target:
      kind: PersistentVolumeClaim
      name: paperless-media
resources:
  - clusterrole.yaml
  - clusterrolebinding.yaml
  - cronjob.yml
  - networkpolicy/allow-paperless-backup-to-api-server.yml
  - persistentvolume.yml
  - pvc.yml
  - serviceaccount.yml
