---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: paperless-backup-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: paperless-backup-role
subjects:
  - kind: ServiceAccount
    name: paperless-backup-serviceaccount
