---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: paperless-backup-role
rules:
  - apiGroups:
      - ''
    resourceNames:
      - paperless-0
    resources:
      - pods
    verbs:
      - get
  - apiGroups:
      - ''
    resourceNames:
      - paperless-0
    resources:
      - pods/exec
    verbs:
      - create
