---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

configMapGenerator:
  - name: ttl-registry-configmap
    files:
      - configmap/registry/config.yml
  - name: ttl-registry-scripts-configmap
    files:
      - configmap/registry/entrypoint.sh
      - configmap/registry/gc.sh
      - configmap/registry/substitute-config.sh
resources:
  - deployment/hooks.yml
  - deployment/reaper.yml
  - deployment/registry.yml
  - redis.yml
  - service/hooks.yml
  - service/reaper.yml
  - service/registry.yml
