---
apiVersion: redis.redis.opstreelabs.in/v1beta2
kind: Redis
metadata:
  name: ttl-redis
spec:
  kubernetesConfig:
    image: quay.io/opstree/redis
    imagePullPolicy: IfNotPresent
  podSecurityContext:
    fsGroup: 1000
    runAsNonRoot: true
    runAsUser: 1000
  securityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL
    readOnlyRootFilesystem: false
    seccompProfile:
      type: RuntimeDefault
  storage:
    volumeClaimTemplate:
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
        storageClassName: longhorn-unencrypted