---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: deny-from-other-namespaces-networkpolicy
spec:
  ingress:
    - from:
        - podSelector: {}
  podSelector:
    matchLabels:
  policyTypes:
    - Ingress
