---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

components:
  - ../../../components/dockerhub-proxy
images:
  - name: busybox
    newTag: 1.38.0@sha256:fd8d9aa63ba2f0982b5304e1ee8d3b90a210bc1ffb5314d980eb6962f1a9715d
  - name: ghcr.io/distribution/distribution
    newTag: 3.1.1@sha256:bca24727f4002e51f959c18c42e816e4d1078198081a9837e16b8b7d7e43ebf8
namespace: dockerhub-proxy
patches:
  - path: patches/configure-registry-deployment.yml
    target:
      kind: Deployment
      name: proxy-registry
  - path: patches/configure-registry-service.yml
    target:
      kind: Service
      name: proxy-registry
resources:
  - namespace.yml
  - certificate.yml
