---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

components:
  - ../../../components/dockerhub-proxy
images:
  - name: busybox
    newTag: 1.38.0@sha256:fd7dc98638c8e305f4dc34e979f1c0fdfdcaeb0fbf8fcff77ae834b6da3d7e6e
  - name: ghcr.io/distribution/distribution
    newTag: 3.1.2@sha256:d106962e6fe3fa69c178cec77eeeee5edb626b8df6535b7bd6b95e658a0a5ca9
namespace: dockerhub-proxy
patches:
  - path: patches/configure-registry-deployment.yml
    target:
      kind: Deployment
      name: proxy-registry
  - path: patches/configure-registry-service.yml
    target:
      kind: Service
      name: proxy-registry
resources:
  - namespace.yml
  - certificate.yml
