---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: forgejo-runners-restricted

components:
  - ../../../components/forgejo-runner-registry-config
  - ../../../components/forgejo-runner-worker-rbac
  - ../../../components/networkpolicy-allow-forgejo-connection-manager-to-api-server
  - ../../../components/networkpolicy-allow-forgejo-runners-to-forgejo-runner-dns
  - ../../../components/networkpolicy-allow-forgejo-runner-operator-to-traefik
  - ../../../components/networkpolicy-allow-forgejo-workflow-job-to-internet
  - ../../../components/networkpolicy-allow-forgejo-workflow-job-to-traefik-ci
  - ../../../components/networkpolicy-allow-workflow-job-to-dockerhub-proxy
  - ../../../components/networkpolicy-deny-all
  - ../../../components/pod-security-enforce-restricted

configurations:
  - kustomizeconfig.yml

images:
  - name: connection-manager
    newName: code.tswn.us/marinatedconcrete/forgejo-runner-operator/connection-manager
    newTag: v0.7.0@sha256:a39ece9506f91b6ed5e3bddb8497b3e07349a44e40a2c4e9ac4c7b9920583813
  - name: job-executor
    newName: code.tswn.us/marinatedconcrete/forgejo-runner-operator/job-executor
    newTag: v0.7.0@sha256:e3a3f41fa5130576e01f43899a37b8cc09a7f40ee8c9d905f88152fbdf16c4bf

resources:
  - namespace.yml
  - connection.yml
  - networkpolicy/allow-connection-manager-and-job-executor-to-coredns.yml
  - serviceaccount.yml
  - worker.yml
