---
apiVersion: operator.kairos.io/v1alpha1
kind: NodeOpUpgrade
metadata:
  name: kairos-upgrade-workers-mack-20260903
spec:
  concurrency: 1
  image: ghcr.io/sdwilsh/mack-kairos:latest.20260903@sha256:ea72c35b4d39815f56b4634671db95910f8e0b5894c15ccc458733abaa5061ca
  nodeSelector:
    matchExpressions:
      - key: node-role.kubernetes.io/control-plane
        operator: DoesNotExist
  stopOnFailure: true
  upgradeRecovery: true
