---
apiVersion: operator.kairos.io/v1alpha1
kind: NodeOpUpgrade
metadata:
  name: kairos-upgrade-workers-0.8.1
spec:
  concurrency: 1
  image: ghcr.io/marinatedconcrete/kairos-fedora:0.8.1
  nodeSelector:
    matchExpressions:
      - key: node-role.kubernetes.io/control-plane
        operator: DoesNotExist
  stopOnFailure: true
