---
namespaceOverride: monitoring

collectors:
  - deployments
  - endpointslices
  - leases
  - nodes
  - pods
  - services

priorityClassName: application-infra

prometheus:
  monitor:
    enabled: true
