---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

images:
 - name: ghcr.io/kube-vip/kube-vip
   newTag: v0.9.0@sha256:b8ca3bf3d7d14cab890ca7696e721f718fa23c57bce9268aebc72de04617335f
resources:
 - namespace.yml
 - rbac.yml
 - daemonset.yml
 - podmonitor.yml
