---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

components:
  - ../../../components/authelia
  - ../../../components/cnpg-backup
  - ../../../components/lldap
configMapGenerator:
  - name: authelia-configmap
    files:
      - configmap/authelia/config.yml
images:
  - name: postgres
    newTag: 17@sha256:2cd82735a36356842d5eb1ef80db3ae8f1154172f0f653db48fde079b2a0b7f7
  - name: quay.io/opstree/redis-sentinel
    newTag: v8.4.2@sha256:093fe87268d612b6a61704334f6f6a22e8110955dae4f84814f0b3dee79680a6
  - name: quay.io/opstree/redis
    newTag: v8.4.2@sha256:eba9bac8aab170698b7276ba1608ad40268ef597c73925576a533940e49287db
namespace: auth
patches:
  # authelia
  - path: patches/authelia/add_config.yml
    target:
      kind: Deployment
      name: authelia-deployment
  # cnpg
  - path: patches/cnpg/set_backup_path.yml
    target:
      kind: ObjectStore
      name: garage-objectstore
  # lldap
  - path: patches/lldap/add_config.yml
    target:
      kind: Deployment
      name: lldap-deployment
  - path: patches/lldap/add_ldaps_for_deployment.yml
    target:
      kind: Deployment
      name: lldap-deployment
  - path: patches/lldap/add_ldaps_for_service.yml
    target:
      kind: Service
      name: lldap-svc
  - path: patches/lldap/add_postgres.yml
    target:
      kind: Deployment
      name: lldap-deployment
  - path: patches/lldap/add_smtp.yml
    target:
      kind: Deployment
      name: lldap-deployment
resources:
  - namespace.yml
  - certificate/lldap.yml
  - cnpg/cluster/authelia.yml
  - cnpg/cluster/lldap.yml
  - cnpg/podmonitor/authelia.yml
  - cnpg/podmonitor/lldap.yml
  - cnpg/scheduledbackup/authelia.yml
  - cnpg/scheduledbackup/lldap.yml
  - ingress/authelia.yml
  - ingress/lldap.yml
  - middleware/forwardauth.yml
  - redisreplication.yml
  - redissentinel.yml
