---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

components:
  - ../../../components/authelia
  - ../../../components/cnpg-backup
  - ../../../components/lldap
  - ../../../components/networkpolicy-allow-from-cnpg-operator
  - ../../../components/networkpolicy-allow-from-prometheus-to-cnpg-cluster
  - ../../../components/networkpolicy-allow-from-traefik
  - ../../../components/networkpolicy-allow-to-coredns
  - ../../../components/networkpolicy-allow-to-proton-bridge
  - ../../../components/networkpolicy-allow-within-this-namespace
  - ../../../components/networkpolicy-deny-all
  - ../../../components/pod-security-enforce-restricted
configMapGenerator:
  - name: authelia-configmap
    files:
      - configmap/authelia/config.yml
images:
  - name: docker.io/bitnami/kubectl
    newTag: latest@sha256:e0fcb25c485a8ad0665d0dd4b4a67cefb6baee32b0e3b19f54f1b468c49c1ed5
  - name: postgres
    newTag: 18@sha256:22c89fe0d0f507606260237fd55e51f6137f58b2d5bcf6152242b96d9fe8f9a4
  - name: quay.io/opstree/redis-sentinel
    newTag: v8.10.1@sha256:99c6953e947b8e958198b6670d44800f388240a5e1939414be39a74c05953c0e
  - name: quay.io/opstree/redis
    newTag: v8.10.1@sha256:d3ef5a7f11eb501034b6612b842c864e1946088c52c04b29a22f38b1fe37c99b
namespace: auth
patches:
  # authelia
  - path: patches/authelia/add_config.yml
    target:
      kind: Deployment
      name: authelia-deployment
  # cnpg
  - path: patches/cnpg/set_backup_path.yml
    target:
      kind: ObjectStore
      name: garage-objectstore
  # lldap
  - path: patches/lldap/add_config.yml
    target:
      kind: Deployment
      name: lldap-deployment
  - path: patches/lldap/add_ldaps_for_deployment.yml
    target:
      kind: Deployment
      name: lldap-deployment
  - path: patches/lldap/add_ldaps_for_service.yml
    target:
      kind: Service
      name: lldap-svc
  - path: patches/lldap/add_postgres.yml
    target:
      kind: Deployment
      name: lldap-deployment
  - path: patches/lldap/add_smtp.yml
    target:
      kind: Deployment
      name: lldap-deployment
  - path: patches/set_traefik_networkpolicy_podselector.yml
    target:
      kind: NetworkPolicy
      name: allow-from-traefik-networkpolicy
replacements:
  - source:
      fieldPath: spec.selector
      kind: Deployment
      name: authelia-deployment
    targets:
      - fieldPaths:
          - spec.podSelector
        select:
          kind: NetworkPolicy
          name: allow-to-proton-bridge-networkpolicy
resources:
  - namespace.yml
  - certificate/lldap.yml
  - cnpg/backup/authelia.yml
  - cnpg/backup/lldap.yml
  - cnpg/cluster/authelia.yml
  - cnpg/cluster/lldap.yml
  - cnpg/podmonitor/authelia.yml
  - cnpg/podmonitor/lldap.yml
  - cnpg/scheduledbackup/authelia.yml
  - cnpg/scheduledbackup/lldap.yml
  - ingress/authelia.yml
  - ingress/lldap.yml
  - middleware/forwardauth.yml
  - networkpolicy/allow-to-and-from-redis-operator.yml
  - networkpolicy/allow-to-lldap-from-consumers.yml
  - redisreplication.yml
