---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

components:
  - ../../../components/authelia
  - ../../../components/cnpg-backup
  - ../../../components/lldap
  - ../../../components/networkpolicy-allow-from-cnpg-operator
  - ../../../components/networkpolicy-allow-from-prometheus-to-cnpg-cluster
  - ../../../components/networkpolicy-allow-from-traefik
  - ../../../components/networkpolicy-allow-within-this-namespace
  - ../../../components/networkpolicy-deny-all
configMapGenerator:
  - name: authelia-configmap
    files:
      - configmap/authelia/config.yml
images:
  - name: docker.io/bitnami/kubectl
    newTag: latest@sha256:558420daf32bbc382e3e9af4537f4073085b336ddd47399a3b70e70087115978
  - name: postgres
    newTag: 18@sha256:22c89fe0d0f507606260237fd55e51f6137f58b2d5bcf6152242b96d9fe8f9a4
  - name: quay.io/opstree/redis-sentinel
    newTag: v8.6.2@sha256:c7e3262f5d791abf49f7b207af75bc0966a324b31f13f22e3a29bdc27d734a5b
  - name: quay.io/opstree/redis
    newTag: v8.6.2@sha256:5f79911253cb74636e8e97555b08095902d46a835c6423adb123295b00ba70d7
namespace: auth
patches:
  # authelia
  - path: patches/authelia/add_config.yml
    target:
      kind: Deployment
      name: authelia-deployment
  # cnpg
  - path: patches/cnpg/set_backup_path.yml
    target:
      kind: ObjectStore
      name: garage-objectstore
  # lldap
  - path: patches/lldap/add_config.yml
    target:
      kind: Deployment
      name: lldap-deployment
  - path: patches/lldap/add_ldaps_for_deployment.yml
    target:
      kind: Deployment
      name: lldap-deployment
  - path: patches/lldap/add_ldaps_for_service.yml
    target:
      kind: Service
      name: lldap-svc
  - path: patches/lldap/add_postgres.yml
    target:
      kind: Deployment
      name: lldap-deployment
  - path: patches/lldap/add_smtp.yml
    target:
      kind: Deployment
      name: lldap-deployment
replacements:
  - source:
      fieldPath: spec.selector
      kind: Deployment
      name: authelia-deployment
    targets:
      - fieldPaths:
          - spec.podSelector
        select:
          kind: NetworkPolicy
          name: allow-from-traefik-networkpolicy
resources:
  - namespace.yml
  - certificate/lldap.yml
  - cnpg/backup/authelia.yml
  - cnpg/backup/lldap.yml
  - cnpg/cluster/authelia.yml
  - cnpg/cluster/lldap.yml
  - cnpg/podmonitor/authelia.yml
  - cnpg/podmonitor/lldap.yml
  - cnpg/scheduledbackup/authelia.yml
  - cnpg/scheduledbackup/lldap.yml
  - ingress/authelia.yml
  - ingress/lldap.yml
  - middleware/forwardauth.yml
  - redisreplication.yml
  - redissentinel.yml
