---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

components:
  - ../../../components/cnpg-backup
  - ../../../components/networkpolicy-allow-from-cnpg-operator
  - ../../../components/networkpolicy-allow-from-prometheus-to-cnpg-cluster
  - ../../../components/networkpolicy-allow-from-traefik
  - ../../../components/networkpolicy-allow-to-api-server
  - ../../../components/networkpolicy-allow-to-coredns
  - ../../../components/networkpolicy-allow-to-internet
  - ../../../components/networkpolicy-allow-within-this-namespace
  - ../../../components/networkpolicy-deny-all
  - ../../../components/pod-security-enforce-restricted
configMapGenerator:
  # `providers` are not declared so they can live in the database and not be
  # prune because the `source_of_truth` is this config file.
  - name: bifrost-config-configmap
    files:
      - configmap/config.json
images:
  - name: docker.io/bitnami/kubectl
    newTag: latest@sha256:b29d8c1665b70817259ceecaea16ab27aab6368b48daf485d19436c809067492
  - name: docker.io/maximhq/bifrost
    newTag: v2.1.1@sha256:9e65eb4d0b292c25aaf46d194c705344f19c833a29e30155038bbe551eac7245
  - name: postgres
    newTag: 18@sha256:4ef4dbc939d61acea57712655ddb4b4ab27419c913f94cca0cd57cb3ea3c2280
namespace: bifrost
patches:
  - path: patches/cnpg/set_backup_path.yml
    target:
      kind: ObjectStore
      name: garage-objectstore
replacements:
  - source:
      fieldPath: spec.selector
      kind: Deployment
      name: bifrost-deployment
    targets:
      - fieldPaths:
          - spec.podSelector
        select:
          kind: NetworkPolicy
          name: allow-from-traefik-networkpolicy
      - fieldPaths:
          - spec.podSelector
        select:
          kind: NetworkPolicy
          name: allow-to-internet-networkpolicy
resources:
  - namespace.yml
  - cnpg/backup.yml
  - cnpg/cluster.yml
  - cnpg/podmonitor.yml
  - cnpg/scheduledbackup.yml
  - deployment.yml
  - ingress/bifrost-api.yml
  - ingress/bifrost.yml
  - networkpolicy/allow-from-prometheus.yml
  - networkpolicy/allow-to-mcp-servers.yml
  - podmonitor.yml
  - prometheusrule.yml
  - service.yml
