---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: bifrost-podmonitor
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: bifrost
  podMetricsEndpoints:
    - path: /metrics
      port: web
      scheme: http
