---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

configMapGenerator:
  - name: mosquitto-default-config-configmap
    files:
      - configmap/default-config/mosquitto.conf
  - name: mosquitto-scripts-configmap
    files:
      - configmap/scripts/create_password.conf.sh
images:
  - name: eclipse-mosquitto
    newTag: 2.0.22@sha256:199ea8ef2e35ec2b1b37e59cfd1dbae538ed4dfa4a2251a121a52215a6248a21
resources:
  - statefulset.yml
  - service.yml
