---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kairos-operator
resources:
  - https://github.com/kairos-io/kairos-operator/config/default?ref=v0.1.0-beta6
  - nodeopupgrade.yml
