---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
  - name: quay.io/kairos/operator
    newTag: v0.2.2@sha256:854198e1e418315c49b55595e0268ca98ea0729403d75cdf17e3f55aabddb3b9
namespace: kairos-operator
resources:
  - https://github.com/kairos-io/kairos-operator/config/default?ref=v0.2.2
  - nodeopupgrade/controlplane.yml
  - nodeopupgrade/workers.yml
