---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

components:
  - ../../../components/codegen-linux-mcp-prod
  - ../../../components/networkpolicy-allow-from-bifrost
  - ../../../components/networkpolicy-allow-from-traefik
  - ../../../components/networkpolicy-allow-to-coredns
  - ../../../components/networkpolicy-deny-all
  - ../../../components/pod-security-enforce-restricted
images:
  - name: quay.io/redhat-services-prod/rhel-lightspeed-tenant/linux-mcp-server
    newTag: 1.7.0@sha256:8fdd597785d2863154e0b9d6e10b5ed6a42feee1f4fcc684f3ac0c5934d6b8d5
namespace: linux-mcp
resources:
  - namespace.yml
  - deployment.yml
  - egress-service.yml
  - ingress.yml
  - service.yml
