---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

components:
  - ../../../components/cnpg-backup
  - ../../../components/networkpolicy-allow-from-cnpg-operator
  - ../../../components/networkpolicy-allow-from-prometheus-to-cnpg-cluster
  - ../../../components/networkpolicy-allow-from-traefik
  - ../../../components/networkpolicy-allow-to-coredns
  - ../../../components/networkpolicy-allow-to-garage
  - ../../../components/networkpolicy-allow-to-traefik
  - ../../../components/networkpolicy-allow-within-this-namespace
  - ../../../components/networkpolicy-deny-all
  - ../../../components/pod-security-enforce-restricted
helmCharts:
  - name: forgejo
    version: 17.1.2
    repo: oci://code.forgejo.org/forgejo-helm
    releaseName: forgejo
    valuesFile: values.yml
images:
  - name: docker.io/bitnami/kubectl
    newTag: latest@sha256:558420daf32bbc382e3e9af4537f4073085b336ddd47399a3b70e70087115978
namespace: forgejo
patches:
  - path: patches/cnpg/set_backup_path.yml
    target:
      kind: ObjectStore
      name: garage-objectstore
replacements:
  - source:
      fieldPath: spec.template.spec.containers.[name=forgejo].ports.[name=http].name
      kind: Deployment
      name: forgejo
    targets:
      - fieldPaths:
          - spec.ingress.0.ports.[port=web].port
        select:
          kind: NetworkPolicy
          name: allow-from-traefik-networkpolicy
  - source:
      fieldPath: spec.selector
      kind: Deployment
      name: forgejo
    targets:
      - fieldPaths:
          - spec.podSelector
        select:
          kind: NetworkPolicy
          name: allow-from-traefik-networkpolicy
      - fieldPaths:
          - spec.podSelector
        select:
          kind: NetworkPolicy
          name: allow-to-garage-networkpolicy
      - fieldPaths:
          - spec.podSelector
        select:
          kind: NetworkPolicy
          name: allow-to-traefik-networkpolicy
resources:
  - namespace.yml
  - cnpg/backup.yml
  - cnpg/cluster.yml
  - cnpg/podmonitor.yml
  - cnpg/scheduledbackup.yml
