---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

components:
  - ../../../components/cnpg-backup
  - ../../../components/cnpg-podmonitor
  - ../../../components/networkpolicy-allow-from-cnpg-operator
  - ../../../components/networkpolicy-allow-from-traefik
  - ../../../components/networkpolicy-allow-from-prometheus-to-cnpg-cluster
  - ../../../components/networkpolicy-allow-to-api-server
  - ../../../components/networkpolicy-allow-to-coredns
  - ../../../components/networkpolicy-allow-to-internet
  - ../../../components/networkpolicy-allow-within-this-namespace
  - ../../../components/networkpolicy-deny-all
  - ../../../components/pod-security-enforce-restricted
  - ../../../components/spoolman
images:
  - name: docker.io/bitnami/kubectl
    newTag: latest@sha256:6e9c5284a0dac06e84de9f4d97852d2e6513442ee7ec3a66d35009eec86e1e62
  - name: ghcr.io/donkie/spoolman
    newTag: 0.26.1@sha256:cf9b41e17b93ce7d4ca584d9809142f8918fd290f2cd7d3b8b12ff76c75482f0
  - name: postgres
    newTag: 18@sha256:86c951e05bf56c93d95d397747fb8820ac76cc3bedb78f43abd83eedbe3666ae
namespace: 3d-printing
patches:
  - path: patches/cnpg/set_backup_path.yml
    target:
      kind: ObjectStore
      name: garage-objectstore
  - path: patches/spoolman/set_database.yml
    target:
      kind: StatefulSet
      name: spoolman-statefulset
  - path: patches/spoolman/add_traefik_route_label.yml
    target:
      kind: StatefulSet
      name: spoolman-statefulset
  - path: patches/spoolman/add_internet_client_label.yml
    target:
      kind: StatefulSet
      name: spoolman-statefulset
replacements:
  - source:
      fieldPath: spec.template.spec.containers.[name=spoolman].ports.[name=spoolman-web].name
      kind: StatefulSet
      name: spoolman-statefulset
    targets:
      - fieldPaths:
          - spec.ingress.0.ports.[port=web].port
        select:
          kind: NetworkPolicy
          name: allow-from-traefik-networkpolicy
resources:
  - namespace.yml
  - cnpg/backup.yml
  - cnpg/cluster.yml
  - cnpg/scheduledbackup.yml
  - ingress.yml
  - middleware.yml
