---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

components:
  - ../../../components/cnpg-backup
  - ../../../components/spoolman
images:
  - name: docker.io/bitnami/kubectl
    newTag: latest@sha256:323998cf83a2332f6761706df910870a3fa24dd8d4b999db977aa322de553399
  - name: ghcr.io/donkie/spoolman
    newTag: 0.23.1@sha256:c798bcc19194949962044459e4b43c09d667d084ae9c2c2e0187a42c36d43d9e
  - name: postgres
    newTag: 18@sha256:29ee7bb30d804447dc9a91fd0d74322ae1dc3a4072cc6346f70a5ed6e783b565
namespace: 3d-printing
patches:
  - path: patches/cnpg/set_backup_path.yml
    target:
      kind: ObjectStore
      name: garage-objectstore
  - path: patches/spoolman/set_database.yml
    target:
      kind: StatefulSet
      name: spoolman-statefulset
resources:
  - namespace.yml
  - cnpg/backup.yml
  - cnpg/cluster.yml
  - cnpg/podmonitor.yml
  - cnpg/scheduledbackup.yml
  - ingress.yml
  - middleware.yml
