---
# The prefix for home folders on this system.
# common__home_prefix: /home/
common__home_prefix: /home/

# Groups to create.  For example:
# common__unix_groups:
#   - name: "ansible"
#     gid: 2000
#     sudo: true
common__unix_groups: []

# Users to create.  `extra_groups` and `authorized_keys` are both optional.
# For example:
# common__unix_users:
#   - name: "ansible"
#     uid: 2000
#     extra_groups:
#       - adm
#     authorized_keys:
#       - ssh-ed25519 AAAA...
common__unix_users: []

# Host-specific groups to create.  For example:
# common__unix_groups:
#   - name: someuser
#     gid: 9000
#     sudo: true
common__host_unix_groups: []

# Host-specific users to create.  A group file can also set this, for a set of
# hosts that share an account.  A `host_vars` file then replaces it, and does
# not add to it.  Takes the same keys as `common__unix_users`.  For example:
# common__host_unix_users:
#   - name: someuser
#     uid: 9000
common__host_unix_users: []