---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: controller-manager
  labels:
    app.kubernetes.io/name: forgejo-runner-operator
    app.kubernetes.io/component: controller-manager
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: leader-election-role
  labels:
    app.kubernetes.io/name: forgejo-runner-operator
    app.kubernetes.io/component: controller-manager
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: leader-election-rolebinding
  labels:
    app.kubernetes.io/name: forgejo-runner-operator
    app.kubernetes.io/component: controller-manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: leader-election-role
subjects:
  - kind: ServiceAccount
    name: controller-manager
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-cache-role
  labels:
    app.kubernetes.io/name: forgejo-runner-operator
    app.kubernetes.io/component: controller-manager
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - serviceaccounts
      - services
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - forgejo.tswn.us
    resources:
      - connections
      - workers
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - rolebindings
      - roles
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: manager-cache-rolebinding
  labels:
    app.kubernetes.io/name: forgejo-runner-operator
    app.kubernetes.io/component: controller-manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: manager-cache-role
subjects:
  - kind: ServiceAccount
    name: controller-manager
    namespace: forgejo-runner-operator
