---
apiVersion: monitoring.coreos.com/v1alpha1 
kind: ScrapeConfig
metadata:
  name: kubernetes-pods-scrapeconfig
spec:
  jobName: kubernetes-pods
  kubernetesSDConfigs:
    - role: Pod
  relabelings:
    - action: keep
      sourceLabels: [__meta_kubernetes_namespace]
      regex: .+
