---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

components:
  - ../../../components/cnpg-backup
  - ../../../components/frigate
  - ../../../components/mosquitto
  - ../../../components/networkpolicy-allow-from-cnpg-operator
  - ../../../components/networkpolicy-allow-from-prometheus-to-cnpg-cluster
  - ../../../components/networkpolicy-allow-from-traefik
  - ../../../components/networkpolicy-allow-to-coredns
  - ../../../components/networkpolicy-allow-within-this-namespace
  - ../../../components/networkpolicy-deny-all
  - ../../../components/pod-security-enforce-baseline
configMapGenerator:
  - files:
      - configmap/frigate/config.yml
    name: frigate-configmap
  - files:
      - configmap/mosquitto-config/homeassistant.conf
    name: mosquitto-config-configmap
images:
  - name: busybox
    newTag: 1.38.0@sha256:dc2d74b28e4cf8984fa52af1f39bc7c3d9c73760b41a74d629f5d11b1ab28616
  - name: docker.io/bitnami/kubectl
    newTag: latest@sha256:65447dcbb2813878e22265949a4ba4cca02f8d008ff3fe66a25354b511f28015
namespace: homeassistant
patches:
  # cnpg
  - path: patches/cnpg/set_backup_path.yml
    target:
      kind: ObjectStore
      name: garage-objectstore
  # frigate
  - path: patches/frigate/add_frigate_env_vars.yml
    target:
      kind: StatefulSet
      name: frigate-statefulset
  - path: patches/frigate/set_frigate_shm_size.yml
    target:
      kind: StatefulSet
      name: frigate-statefulset
  - path: patches/frigate/avoid_control_plane.yml
    target:
      kind: StatefulSet
      name: frigate-statefulset
  # mosquitto
  - path: patches/mosquitto/add_custom_config.yml
    target:
      kind: StatefulSet
      name: mosquitto-statefulset
  - path: patches/set_traefik_networkpolicy_pods_and_ports.yml
    target:
      kind: NetworkPolicy
      name: allow-from-traefik-networkpolicy
resources:
  - namespace.yml
  - cnpg/backup.yml
  - cnpg/certificate.yml
  - cnpg/cluster.yml
  - cnpg/ingressroutetcp.yml
  - cnpg/middlewaretcp.yml
  - cnpg/podmonitor.yml
  - cnpg/scheduledbackup.yml
  - cnpg/tlsoption.yml
  - ingress.yml
  - ingressroutetcp.yml
  - networkpolicy/allow-to-cameras-from-frigate.yml
