---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

components:
  - ../../../components/cnpg-backup
  - ../../../components/frigate
  - ../../../components/mosquitto
  - ../../../components/networkpolicy-allow-from-cnpg-operator
  - ../../../components/networkpolicy-allow-from-prometheus-to-cnpg-cluster
  - ../../../components/networkpolicy-allow-within-this-namespace
  - ../../../components/networkpolicy-deny-all
  - ../../../components/pod-security-enforce-baseline
configMapGenerator:
  - files:
      - configmap/frigate/config.yml
    name: frigate-configmap
  - files:
      - configmap/mosquitto-config/homeassistant.conf
    name: mosquitto-config-configmap
images:
  - name: busybox
    newTag: 1.38.0@sha256:fd8d9aa63ba2f0982b5304e1ee8d3b90a210bc1ffb5314d980eb6962f1a9715d
  - name: docker.io/bitnami/kubectl
    newTag: latest@sha256:558420daf32bbc382e3e9af4537f4073085b336ddd47399a3b70e70087115978
namespace: homeassistant
patches:
  # cnpg
  - path: patches/cnpg/set_backup_path.yml
    target:
      kind: ObjectStore
      name: garage-objectstore
  # frigate
  - path: patches/frigate/add_frigate_env_vars.yml
    target:
      kind: StatefulSet
      name: frigate-statefulset
  - path: patches/frigate/set_frigate_shm_size.yml
    target:
      kind: StatefulSet
      name: frigate-statefulset
  # mosquitto
  - path: patches/mosquitto/add_custom_config.yml
    target:
      kind: StatefulSet
      name: mosquitto-statefulset
resources:
  - namespace.yml
  - cnpg/backup.yml
  - cnpg/certificate.yml
  - cnpg/cluster.yml
  - cnpg/ingressroutetcp.yml
  - cnpg/middlewaretcp.yml
  - cnpg/podmonitor.yml
  - cnpg/scheduledbackup.yml
  - cnpg/tlsoption.yml
  - ingress.yml
  - ingressroutetcp.yml
