---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

components:
  - ../../../components/atuin
  - ../../../components/cnpg-backup
  - ../../../components/cnpg-podmonitor
  - ../../../components/networkpolicy-allow-from-cnpg-operator
  - ../../../components/networkpolicy-allow-from-traefik
  - ../../../components/networkpolicy-allow-from-prometheus-to-cnpg-cluster
  - ../../../components/networkpolicy-allow-to-api-server
  - ../../../components/networkpolicy-allow-to-coredns
  - ../../../components/networkpolicy-allow-within-this-namespace
  - ../../../components/networkpolicy-deny-all
  - ../../../components/pod-security-enforce-restricted
images:
  - name: busybox
    newTag: 1.38.0@sha256:dc2d74b28e4cf8984fa52af1f39bc7c3d9c73760b41a74d629f5d11b1ab28616
  - name: docker.io/bitnami/kubectl
    newTag: latest@sha256:b29d8c1665b70817259ceecaea16ab27aab6368b48daf485d19436c809067492
  - name: ghcr.io/atuinsh/atuin
    newTag: 18.22.0@sha256:1e94eb5c2fb6bb1e46da2591648efa11aa9507fcd80ddf812e4acbfe51d8a840
  - name: postgres
    newTag: 18@sha256:4ef4dbc939d61acea57712655ddb4b4ab27419c913f94cca0cd57cb3ea3c2280
namespace: atuin
patches:
  - path: patches/atuin/add_traefik_route_label.yml
    target:
      kind: Deployment
      name: atuin-deployment
  - path: patches/atuin/set_config_env.yml
    target:
      kind: Deployment
      name: atuin-deployment
  - path: patches/cnpg/set_backup_path.yml
    target:
      kind: ObjectStore
      name: garage-objectstore
resources:
  - namespace.yml
  - cnpg/backup.yml
  - cnpg/cluster.yml
  - cnpg/scheduledbackup.yml
  - ingress.yml
