---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

components:
  - ../../../components/atuin
  - ../../../components/cnpg-backup
images:
  - name: busybox
    newTag: 1.37.0@sha256:b3255e7dfbcd10cb367af0d409747d511aeb66dfac98cf30e97e87e4207dd76f
  - name: ghcr.io/atuinsh/atuin
    newTag: 18.13.6@sha256:9bde3fe6b1633c357cb19c07ea49bb9834720e8ff42d04b39ad7865155581150
  - name: postgres
    newTag: 17@sha256:7ad98329d513dd497293b951c195ca354274a77f12ddbbbbf85e68a811823d72
namespace: atuin
patches:
  - path: patches/atuin/set_config_env.yml
    target:
      kind: Deployment
      name: atuin-deployment
  - path: patches/cnpg/set_backup_path.yml
    target:
      kind: ObjectStore
      name: garage-objectstore
resources:
  - namespace.yml
  - cnpg/cluster.yml
  - cnpg/podmonitor.yml
  - cnpg/scheduledbackup.yml
  - ingress.yml
