---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

components:
  - ../../../components/atuin
  - ../../../components/cnpg-backup
images:
  - name: busybox
    newTag: 1.37.0@sha256:1487d0af5f52b4ba31c7e465126ee2123fe3f2305d638e7827681e7cf6c83d5e
  - name: ghcr.io/atuinsh/atuin
    newTag: 18.15.1@sha256:c186d172ff259d4534707bbf1ba74121a45a925653c9bd07869a5e2b898dabe7
  - name: postgres
    newTag: 17@sha256:7ad98329d513dd497293b951c195ca354274a77f12ddbbbbf85e68a811823d72
namespace: atuin
patches:
  - path: patches/atuin/set_config_env.yml
    target:
      kind: Deployment
      name: atuin-deployment
  - path: patches/cnpg/set_backup_path.yml
    target:
      kind: ObjectStore
      name: garage-objectstore
resources:
  - namespace.yml
  - cnpg/cluster.yml
  - cnpg/podmonitor.yml
  - cnpg/scheduledbackup.yml
  - ingress.yml
