---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

components:
  - ../../../components/forgejo-scaled-runner
configMapGenerator:
  - name: runner-config-configmap
    files:
      - configmap/config.yml
  - name: daemon-config-configmap
    files:
      - configmap/daemon.json
      - configmap/registries.conf
      - configmap/storage.conf
images:
  - name: code.forgejo.org/forgejo/runner
    newTag: 12.13.1@sha256:e070b166b921f12a2abef432cf6108e63519d0183722c2a14ecbb8d0b0621652
  - name: docker.io/library/docker
    newTag: 29.6.2-dind-rootless@sha256:212a9e782c7119fd6a212beaab6b7665a29b663d894d0f6201710c89575ad0ae
namespace: forgejo-action-runner
openapi:
  path: openapi.yml
patches:
  - path: patches/configure-scaledjob.yml
    target:
      kind: ScaledJob
      name: forgejo-runner-scaledjob
resources:
  - namespace.yml
