---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: this-is-ignored-but-is-required
spec:
  template:
    spec:
      containers:
        - name: jellyfin
          resources:
            limits:
              amd.com/gpu: 1
            requests:
              amd.com/gpu: 1
      tolerations:
        - effect: NoSchedule
          key: gpu
          operator: Equal
          value: strixhalo
