---
- op: replace
  path: /spec/podSelector
  value:
    matchExpressions:
      - key: app.kubernetes.io/name
        operator: In
        values:
          - jellyfin
          - navidrome
          - tdarr-node
          - tdarr-server
