---
apiVersion: v1
kind: Service
metadata:
  name: proxy-registry
  labels:
    app.kubernetes.io/name: proxy-registry
spec:
  type: ClusterIP
  ports:
    - name: web
      protocol: TCP
      port: 5000
      targetPort: 5000
  selector:
    app.kubernetes.io/name: proxy-registry
