---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

configurations:
  - namereference.yml
configMapGenerator:
  - name: runner-scripts-configmap
    files:
      - configmap/daemon.sh
      - configmap/runner.sh
images:
  - name: code.forgejo.org/forgejo/runner
    newTag: 12.11.1@sha256:a1a2885261a0b8337d4791dd6949651117206741ba66423c24a57c107a64d4a8
  - name: docker.io/library/docker
    newTag: 29.6.1-dind-rootless@sha256:371962f4344295a1eb185f1c9e62064bf4503a7beb8c6e73be3405500041784b
resources:
  - scaledjob.yml
  - triggerauthentication.yml
