---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

configurations:
  - namereference.yml
configMapGenerator:
  - name: runner-scripts-configmap
    files:
      - configmap/daemon.sh
      - configmap/runner.sh
images:
  - name: code.forgejo.org/forgejo/runner
    newTag: 13.0.0@sha256:7fb853bfe73c229be6349398359c0a7bd01fadfd17c106607b2221150b799ed2
  - name: docker.io/library/docker
    newTag: 29.7.1-dind-rootless@sha256:7451e3dc398b11ba2d8183bb7915402683e3d32e5ec8cef835c215f314a65fef
resources:
  - scaledjob.yml
  - triggerauthentication.yml
