---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: nextcloud
    version: 8.2.0
    repo: https://nextcloud.github.io/helm/
    releaseName: nextcloud
    valuesFile: nextcloud-values.yml
images:
  - name: postgres
    newTag: 17@sha256:f337b026cb1fb954a93f2e33a62bf9ea7fffc1dafc1586c53b93922a8d6ee018
namespace: nextcloud
resources:
  - namespace.yml
  - ingress.yml
  - middleware.yml
  - persistentvolume.yml
  - persistentvolumeclaim.yml
  - postgresql.yml
  - redis.yml
