---
name: Devcontainer-based CI
on:
 push:
   branches:
     - main
     - renovate/**
 pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Login to GitHub Container Registry
        uses: docker/login-action@af1e73f918a031802d376d3c8bbc3fe56130a9b0 # v4 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Set up Buildx to use docker-container
        uses: docker/setup-buildx-action@bb05f3f5519dd87d3ba754cc423b652a5edd6d2c # v4.2.0
        with:
          driver: docker-container

      - name: Pre-build image and run lint in dev container
        uses: devcontainers/ci@513af61f4de4f75d37e4438f184ba4358f0fc1ca # v0.3.1900000450
        with:
          cacheFrom: ghcr.io/${{ github.repository }}-devcontainer
          cacheTo: ghcr.io/${{ github.repository }}-devcontainer
          env: |
            CI=1
          imageName: ghcr.io/${{ github.repository }}-devcontainer
          push: filter
          refFilterForPush: refs/heads/main

  quick-lint:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Run quick-lint
        uses: devcontainers/ci@513af61f4de4f75d37e4438f184ba4358f0fc1ca # v0.3.1900000450
        with:
          cacheFrom: ghcr.io/${{ github.repository }}-devcontainer
          env: |
            ANSIBLE_CONFIG=ansible-ci.cfg
            CI=1
          push: never
          runCmd: |
            set -euxo pipefail
            just ansible-lint
            just hadolint
            just justcheck
            just renovate-validate
            just shellcheck

  kustomize-build:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Run kustomize-build
        uses: devcontainers/ci@513af61f4de4f75d37e4438f184ba4358f0fc1ca # v0.3.1900000450
        with:
          cacheFrom: ghcr.io/${{ github.repository }}-devcontainer
          env: |
            CI=1
          push: never
          runCmd: |
            set -euxo pipefail
            just kustomize-build
