---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

components:
  - ../../../components/networkpolicy-allow-to-coredns
  - ../../../components/networkpolicy-allow-to-internet
  - ../../../components/networkpolicy-deny-all
  - ../../../components/olah
  - ../../../components/pod-security-enforce-restricted
images:
  - name: docker.io/xiahan2019/olah
    newTag: 0.5.1@sha256:a5fec886e874ca978a8b011a231337a3d7c8da9ae8a6c283ba2030bf5d259a6b
namespace: olah
patches:
  - path: patches/add_internet_client_label.yml
    target:
      kind: Deployment
      name: olah-deployment
resources:
  - namespace.yml
  - networkpolicy/allow-to-olah-from-consumers.yml
  - persistentvolume.yml
  - persistentvolumeclaim.yml
