---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

components:
  - ../../../components/networkpolicy-allow-to-coredns
  - ../../../components/networkpolicy-allow-to-internet
  - ../../../components/networkpolicy-deny-all
  - ../../../components/olah
  - ../../../components/pod-security-enforce-restricted
images:
  - name: docker.io/xiahan2019/olah
    newTag: 0.5.4@sha256:802ec30637bc37c2766e39d66a6c57e2ba1c97eb6fc2db14c459f7b174372baf
namespace: olah
patches:
  - path: patches/add_internet_client_label.yml
    target:
      kind: Deployment
      name: olah-deployment
resources:
  - namespace.yml
  - networkpolicy/allow-to-olah-from-consumers.yml
  - persistentvolume.yml
  - persistentvolumeclaim.yml
