---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: olah-cache-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 1Ti
  volumeName: olah-cache-pv
